- .gitignore
- src/plugin/controller.ts
> add color value check and set opacity based on that

- package.json
- src/app/components/App.tsx
- src/app/components/EditTokenForm.tsx
- src/app/components/Input.tsx
- src/app/components/Inspector.tsx
- src/app/components/Navbar.tsx
- src/app/components/Textarea.tsx
- src/app/components/TokenButton.tsx
- src/app/components/Tokens.tsx
- src/app/components/Tooltip.tsx
- src/app/components/utils.tsx
- src/app/presets/default.js
- src/app/styles/tailwind.css
- src/plugin/controller.ts
- src/plugin/helpers.ts
- src/plugin/notifiers.ts
- src/plugin/store.ts
- src/plugin/styles.ts
- yarn.lock
Fixes #10 
Covered the biggest obstacles:
> Typography support

- src/app/components/TokenButton.tsx
- src/app/styles/tailwind.css
> fix nested tokens, white tokens

- src/app/components/TokenButton.tsx
- src/app/components/utils.tsx
> changed default behaviour of tokenbutton click

- src/app/components/App.tsx
- src/app/components/Icon.tsx
- src/app/components/Navbar.tsx
- src/app/components/TokenData.tsx
- src/app/components/icons/IconImport.tsx
- src/app/store/TokenContext.tsx
- src/plugin/controller.ts
- src/plugin/notifiers.ts
- src/plugin/styles.ts
> add color styles import

- src/app/components/MoreButton.tsx
- src/app/components/TokenButton.tsx
- src/app/components/TokenListing.tsx
- src/app/components/Tokens.tsx
- src/app/store/TokenContext.tsx
- src/app/styles/tailwind.css
- src/config/properties.js
- src/plugin/node.ts
- src/plugin/pluginData.ts
> Remove tokens in ui

- src/config/default.js
I'm loving this plugin. Thanks for this effort!
> Valid JSON and typo updates

- package.json
- src/app/components/Icon.tsx
- src/app/components/Inspector.tsx
- src/app/components/icons/IconTrash.tsx
- src/app/store/TokenContext.tsx
- src/plugin/controller.ts
- src/plugin/pluginData.ts
Adds ability to remove single tokens from Inspect tab
> add ability to remove single tokens, fixes #27

- package.json
- src/app/components/TokenData.tsx
- src/app/components/TokenListing.tsx
Fixes two bugs with token creation and import
> Fix setting number tokens

- package.json
- src/app/components/Button.tsx
- src/app/components/Initiator.tsx
- src/app/components/JSONEditor.tsx
- src/app/components/Navbar.tsx
- src/app/components/TokenSetSelector.tsx
- src/app/components/Tokens.tsx
- src/app/index.tsx
- src/app/store/TokenContext.tsx
- yarn.lock
Integrates Sentry.io error tracking
> integrate error tracking

- package.json
- src/app/components/TokenListing.tsx
- src/app/store/TokenContext.tsx
Fixes a bug with token modals not closing 🙈
> Fix token modal

- src/app/components/TokenButton.tsx
- src/config/properties.js
- src/plugin/helpers.ts
- src/plugin/node.ts
- src/plugin/setColorValuesOnTarget.ts
- src/plugin/setTextValuesOnTarget.ts
- src/plugin/updateNode.ts
- src/utils/aliases.tsx
- src/utils/uiSettings.ts
- types/state.tsx
- Adds `raw value` option to each token
- Add `tokenName` option to each token
- Adds `description` option to each token
- Allows users to set `fontSize` as `px`, `em`, `rem`
- Allows users to set `spacing`, `sizing`, `borderRadius`, `borderWidth` as `px`
- Allows users to set aliases as `{ }`
> Introduce Documentation Tokens

- src/plugin/node.ts
fixes a bug with old token values when opening these again
> fix empty token objects in initialization

- src/app/components/Tokens.tsx
- src/config/default.json
- src/config/properties.js
- src/config/tokens.js
- src/plugin/removeValuesFromNode.ts
- src/plugin/updateNode.ts
Thanks for this plugin! Our team is starting to use it and is really excited about it. The one thing it is missing from what we'd like is just a box-shadow token. So here is my shot at it 😀 Let me know if I've missing anything. I'm open to naming also, just went with boxShadow for now.
> Add boxShadow Fixes #29

- src/plugin/tokenHelpers.ts
Currently the box shadow doesn't work on the next branch, so I created a quick fix.
Is this ok?
> Fixed issue with boxShadow in next branch

- cypress/integration/tokens.spec.js
- package.json
- src/app/components/TokenListing.tsx
- src/app/components/utils.tsx
- src/config/tokenTypes.js
- src/plugin/figmaTransforms/generic.test.ts
- src/plugin/figmaTransforms/opacity.ts
- Resolves #184 
- Enables % based opacity tokens again
> 53 release hotfixes

- src/utils/uiSettings.ts
> resolves #193

- src/app/components/EditTokenForm.tsx
- src/config/tokenTypes.js
> resolves #199

- script.js
- src/app/components/Initiator.tsx
- src/app/components/Navbar.tsx
- src/app/components/StartScreen.tsx
- src/app/components/StorageItem.tsx
- src/app/components/SyncSettings.tsx
- src/app/components/TokenGroupHeading.tsx
- src/app/components/TokenSetSelector.tsx
- src/app/components/modals/CreateStorageItemModal.tsx
- src/app/components/modals/EditStorageItemModal.tsx
- src/app/store/models/tokenState.tsx
- src/app/store/providers/jsonbin.tsx
- src/app/store/remoteTokens.tsx
- src/app/store/updateSources.tsx
- src/app/store/useManageTokens.tsx
- src/app/store/useStorage.tsx
- src/plugin/notifiers.ts
- src/utils/parseTokenValues.ts
- token-transformer/package.json
- types/api.tsx
- webpack-transform.config.js
Cleans up Sync in preparation for Git sync
> Refactor sync

- src/app/components/TokenButton.tsx
- src/app/components/TokenTooltip.tsx
- src/plugin/tokenHelpers.test.ts
- src/plugin/tokenHelpers.ts
- src/utils/aliases.test.ts
- src/utils/aliases.tsx
Fixes alias calculation so users can use math inside rgba() functions.
The big change here is that getAliasValue doesn't just return the value of the alias, but if that alias contains another alias will also resolve that.
> fix alias calculation

- src/app/components/utils.test.ts
- src/app/components/utils.tsx
- src/plugin/figmaTransforms/colors.test.ts
- src/plugin/figmaTransforms/colors.ts
- src/plugin/tokenHelpers.test.ts
- src/utils/aliases.test.ts
> fix lightOrDark visualization by converting hsla before calculating

- package.json
- src/app/components/BoxShadowInput.tsx
- src/app/components/EditTokenForm.tsx
Small hotfix for editing descriptions and shadow spread label
> Release 70

- src/plugin/NodeManager.ts
This fixes a bug that was introduced in V79 around variants and the new cache.
> Fix cache for variants

- src/app/store/models/uiState.tsx
- src/plugin/controller.ts
- src/plugin/notifiers.ts
- src/types/messages.tsx
- src/utils/uiSettings.ts
> Hotfix for Version 80

- package.json
- src/app/components/TokenTooltip.tsx
- src/app/store/models/uiState.tsx
> Fix inspect

- src/plugin/NodeManager.ts
Fixes a bug where cache of instance nodes wasn't being updated when main component received new tokens
> fix cache bug with instances

- src/plugin/setValuesOnNode.ts
> Fix borders with gradients

- src/app/store/models/tokenState.tsx
- src/app/store/updateSources.tsx
- src/constants/SharedPluginDataKeys.ts
- src/plugin/controller.ts
- src/plugin/node.ts
- src/types/messages.tsx
> Remember last used token sets after plugin relaunch

- .gitignore
- src/app/components/modals/ExportModal.tsx
- src/app/components/utils.tsx
- src/app/store/useTokens.tsx
- src/utils/__snapshots__/convertTokensObjectToResolved.test.ts.snap
- src/utils/convertTokens.tsx
- src/utils/convertTokensObjectToResolved.test.ts
- src/utils/convertTokensObjectToResolved.ts
- src/utils/convertTokensToGroupedObject.ts
- src/utils/formatTokens.test.ts
- src/utils/formatTokens.ts
- src/utils/types.d.ts
- token-transformer/README.md
- token-transformer/index.js
Adds a possibility to expand boxShadow tokens just like the typography tokens.
> Add expandShadow parameter for boxShadow types

- src/app/store/models/tokenState.tsx
- src/app/store/providers/github.tsx
- src/app/store/providers/jsonbin.tsx
- src/app/store/providers/url.tsx
- src/types/messages.tsx
> Treat errors as errors in Figma UI

- src/app/components/AnnotationBuilder.tsx
- src/app/components/Callout.tsx
- src/app/components/ContextMenu.tsx
- src/app/components/Heading.tsx
- src/app/components/InspectorDebugView.tsx
- src/app/components/SyncSettings.tsx
- src/app/components/TokenButton/TokenButton.tsx
- src/app/components/TokenGroupHeading.tsx
- src/hooks/useGetActiveState.ts
Fixes some minor styling issues that occured recently
> Fix styling issues

- src/app/components/Changelog.tsx
Fixes a bug with styling that was introduced on the changelog
> fix: changelog styling

- src/plugin/controller.ts
- src/types/messages.tsx
* Fixed multi-inspector remove selected.
> Fix remove selected

- src/app/components/App.tsx
- src/app/components/Navbar.tsx
- src/app/components/Settings.tsx
- src/app/components/StartScreen.tsx
- src/app/components/SyncSettings.tsx
- src/constants/Tabs.ts
* Combine Sync and Settings Tab
* Removed Sync Tab
* Now on, we redirect users to 'settings' tab instead of 'syncsettings' tab
> feat(Navbar): Combine Sync and Settings Tab

- package.json
- src/app/components/DownshiftInput.tsx
- src/app/components/EditTokenForm.tsx
- src/app/components/Input.tsx
- src/stitches.config.ts
- yarn.lock
* Added Downshift package
* Dropdown and Autosuggest components
> feat(Autocomplete):

- src/app/components/DownshiftInput.tsx
Fixes styling of tokenpicker by changing colors, shadows, removing raw hex values, etc.
> minor fix of tokenpicker styling

- src/utils/__tests__/__snapshots__/convertTokensObjectToResolved.test.ts.snap
- src/utils/__tests__/convertTokensObjectToResolved.test.ts
- src/utils/convertTokensObjectToResolved.ts
- src/utils/convertTokensToGroupedObject.ts
- src/utils/types.d.ts
- token-transformer/README.md
- token-transformer/index.js
> Token Transformer add `resolveReferences`option

- src/app/components/AddLicenseKey/AddLicenseKey.tsx
- src/app/components/App.tsx
* Added the email attribute for LD
* Changed 'beta' to 'license' key
> Add email for LD

- src/app/components/SyncSettings.tsx
- src/app/store/providers/github/github.tsx
- src/app/store/providers/gitlab/gitlab.tsx
- src/app/store/remoteTokens.tsx
fixes old branches showing up in branch selector, basically just moved this from the release-102 branch to the next branch
> fix branches selector

- package.json
- src/app/components/LaunchDarkly/LDIdentifier.tsx
fixes plugin not launching for some users
> fix feature flag validation

- src/app/styles/tailwind.css
> fix scrollbar color

- package.json
- src/plugin/setValuesOnNode.test.ts
- src/plugin/setValuesOnNode.ts
- src/utils/analytics.tsx
> fix set values on node

- src/app/components/BoxShadowInput.tsx
- src/app/components/EditTokenForm.tsx
- src/app/components/SingleBoxShadowInput.tsx
- src/app/components/SingleCompositionTokenForm.tsx
- src/app/components/TypographyInput.tsx
- src/utils/trimValue.test.ts
- src/utils/trimValue.ts
> 432 token values should be trimmed on input and when passing to figma

- src/storage/UrlTokenStorage.ts
> fix: allow complex single file schema in urltokenstorage

- README.md
@six7 Thanks for https://github.com/six7/figma-tokens/issues/1054#issuecomment-1186551040. It worked! I thought this info would be good on the repo's README.
#1054
> docs: Adds Known Issues from plugin docs to README.md

- src/app/components/Button/Button.tsx
- src/app/components/Button/StyledButton.tsx
- src/app/components/StorageItem.test.tsx
- src/app/components/StorageItem.tsx
> 526 allow the currently active sync setting to be deleted

- src/app/components/TokenListing.test.tsx
- src/app/components/TokenListing.tsx
- src/app/components/Tooltip.tsx
> 1016 collapsing all the tokens at once using optionalt+click stopped working since the latest update

- src/app/components/SyncSettings.tsx
> fix jsonbin docs link

- src/app/components/AppContainer/startupProcessSteps/__tests__/pullTokensFactory.test.ts
- src/app/components/AppContainer/startupProcessSteps/pullTokensFactory.ts
> 1144 recover local changes doenst work

- src/utils/convertTokens.tsx
> 1143-114-rc3-tokens-without-type-get-inherittypelevel-added

- src/app/components/Footer.tsx
- src/app/components/PresetProvider/FilePreset.tsx
- src/app/store/models/reducers/tokenState/setTokenData.ts
- src/app/store/models/tokenState.test.ts
- src/app/store/remoteTokens.test.ts
- src/app/store/remoteTokens.tsx
When using remote storage and you have Themes set up the theme selector gets reset after every pull.
> 1131 theme selector gets reset to none after pull from remote

- src/utils/formatTokens.test.ts
- src/utils/formatTokens.ts
When trying to expand and export a typography / boxshadow token which has non resolved value, plugin export strange value.
> 1189 non resolved typographyboxshadow tokens are not exported correctly

- cypress/integration/branches.spec.js
- src/app/components/PushDialog.tsx
- src/app/components/Textarea.tsx
Instead of a text input for the commit message it would be cool if it could be Text area that allows multiline input.
> 1011 add support for multiline commit messages

- src/app/store/providers/__tests__/jsonbin.test.ts
- src/app/store/providers/ado/ado.tsx
- src/app/store/providers/bitbucket/bitbucket.tsx
- src/app/store/providers/github/github.tsx
- src/app/store/providers/gitlab/gitlab.tsx
- src/app/store/remoteTokens.test.ts
Add missing test coverage for gitHub.ts, gitLab.tsx, ado.tsx and jsonbin.tsx.
You can check all three test coverages here.
> Test/GitHub, GitLab, Ado, Jsonbin

- src/app/components/BranchSelector.tsx
https://www.loom.com/share/17706fa5113442a5b3809038d5ca222d
> 1184-pro-feature-create-new-branch-from-ui-issue

- src/utils/trySetStyleId.ts
https://user-images.githubusercontent.com/25951419/193707486-7c8bdfca-8b52-4107-8c97-4e989b32943d.mp4
> 1316-tokens-not-applying

- src/app/components/InspectorDebugView.tsx
- src/app/components/InspectorMultiView.tsx
- src/app/components/TokenGroup/TokenGroupHeading.tsx
- src/app/components/TokenSetItem/StyledButton.tsx
- src/constants/StyleIdBackupKeys.ts
- src/plugin/figmaTransforms/fontWeight.test.ts
- src/plugin/figmaTransforms/fontWeight.ts
- src/plugin/setTextValuesOnTarget.ts
- src/utils/annotations.tsx
Contains some smaller fixes to be released together with #1319 
Fixes #1306 
Fixes token group heading only reacting to clicking the label, not the chevron
Fixes `Semibold` being missing in font weights
Fixes noisy font weight error messages
> fixes for 121

- src/app/components/ContextMenu.tsx
- src/app/components/MoreButton/MoreButton.test.tsx
- src/app/components/MoreButton/MoreButton.tsx
- src/app/components/MoreButton/MoreButtonProperty.tsx
- src/app/hooks/usePropertiesForType.test.ts
- src/app/hooks/usePropertiesForType.ts
- src/plugin/setValuesOnNode.test.ts
- src/plugin/setValuesOnNode.ts
- src/types/properties/PropertyObject.ts
https://user-images.githubusercontent.com/25951419/194060011-e7e36a31-13e7-4a4c-85e4-9cd63752ffe5.mp4
> 110 support multi value radii and spacing tokens

- src/plugin/setTextValuesOnTarget.test.ts
- src/plugin/setTextValuesOnTarget.ts
https://user-images.githubusercontent.com/25951419/194247298-38830679-404e-4808-ba58-5f9d97063069.mp4
> support font familty fall back

- src/app/components/AddLicenseKey/AddLicenseKey.test.tsx
- src/app/components/AddLicenseKey/AddLicenseKey.tsx
- src/app/components/Input.tsx
> 1293 changes to license key display

- src/app/components/AddLicenseKey/AddLicenseKey.tsx
- src/app/components/Button/StyledButton.tsx
- src/app/components/ConfirmDialog.tsx
- src/app/components/EditTokenForm.tsx
- src/app/components/Heading.tsx
- src/app/components/Input.tsx
- src/app/components/OnboardingFlow.tsx
- src/app/components/Settings/Settings.tsx
- src/app/components/SyncSettings.tsx
- src/app/components/Tokens.tsx
- src/app/hooks/usePropertiesForType.ts
- src/app/store/useTokens.tsx
- src/plugin/setImageValuesOnTarget.ts
- src/plugin/setValuesOnNode.ts
Contains just a few UI fixes I encountered
> Minor fixes for 123

- src/app/components/AppContainer/__tests__/AppContainerIntegration.test.tsx
- src/app/store/models/effects/tokenState/index.ts
- src/app/store/models/effects/tokenState/removeStyleNamesFromThemes.ts
- src/app/store/models/effects/tokenState/renameStyleNamesToCurrentTheme.ts
- src/app/store/models/reducers/tokenState/index.ts
- src/app/store/models/reducers/tokenState/removeStyleNamesFromThemes.ts
- src/app/store/models/reducers/tokenState/renameStyleNamesToCurrentTheme.ts
- src/app/store/useManageTokens.test.tsx
- src/app/store/useManageTokens.tsx
- src/app/store/useTokens.tsx
- src/plugin/asyncMessageHandlers/syncStyles.ts
- src/plugin/compareStyleWithToken.ts
- src/plugin/syncStyles.test.ts
- src/plugin/syncStyles.ts
- src/plugin/updateColorStyles.ts
- src/types/AsyncMessages.ts
https://www.loom.com/share/2820c621b48849c6b89404716a6269f9
> fix sync styles

- src/app/components/StorageItem.tsx
- src/utils/isSameCredentials.test.ts
- src/utils/isSameCredentials.ts
@six7  Rebased on main branch.
> 356-github-sync-plugin-losing-access-tokens-sometimes

- src/plugin/node.test.ts
While I was browsing source, I found this. 
don't think it is intended, but please feel free to close it or merge :)
> Fix typo in node.test.ts

- src/app/components/OnboardingFlow.test.tsx
Create onboarding flow modal test.
> Onboardingflow test

- src/app/components/EditTokenForm.tsx
https://www.loom.com/share/6b68af030c89402e8b04d9b407dc86d1
> 1386-conflicting-token-group

- .eslintrc.js
- src/plugin/node.ts
- src/plugin/setValuesOnNode.ts
https://www.loom.com/share/c5aaf49cd71f491a92d22efe2e5ff40f
> 1425 gradients cant be used directly in compositions

- src/app/components/SyncSettings.tsx
https://www.loom.com/share/18b12744ef6949e187362a3de832052f
> 1279-switching-from-url-to-local-storage-does-not-make-tokens-writable

- .eslintrc.js
- src/app/components/TokenGroup/TokenGroupHeading.tsx
- src/app/store/models/tokenState.tsx
- src/app/store/useManageTokens.tsx
- src/types/payloads/RenameTokenGroupPayload.ts
https://www.loom.com/share/8851332c3c194d7590e2363ba01a616e
> 1411 when changing a group name let users change the full path

- package.json
- script/release.sh
- src/app/components/Changelog.tsx
- src/app/components/Initiator.tsx
- src/plugin/NodeManager.ts
- src/plugin/__tests__/notifiers.test.ts
- src/plugin/notifiers.ts
- src/plugin/pluginData.ts
- src/plugin/setTextValuesOnTarget.ts
- src/types/messages.tsx
- Fixes a bug when using the new `none` tokens that caused the plugin to stay in `Finding and caching tokens`
> Release 132

- src/app/components/Input.tsx
- src/app/components/StorageItemForm/GenericVersioned.tsx
This resolves https://github.com/tokens-studio/figma-plugin/issues/1504 . It also fixes a minor "bug" if an input ref was not provided but needed for masking
> 1504 Sensitive header support

- src/types/CompositionTokenProperty.ts
- src/utils/alias/__tests__/getAliasValue.test.ts
- src/utils/alias/getAliasValue.ts
https://www.loom.com/share/0267bd50e1d44bbab46b5c2b761e1522
> 1507-border-tokens-dont-work-in-composition-tokens

- src/app/components/BorderTokenForm.tsx
- src/app/components/EditTokenForm.tsx
- src/app/components/ResolvedBorderValueDisplay.tsx
- src/app/components/ResolvedTokenDisplay.tsx
- src/app/components/TokenTooltip/TokenTooltipContentValue.tsx
- src/utils/is/isSingleBorderToken.ts
https://www.loom.com/share/005eb26688804be49fb562c04b122f26
> 1523 border tokens do not offer a way to add alias tokens base 133

- src/app/store/useTokens.test.tsx
- src/app/store/useTokens.tsx
- src/plugin/asyncMessageHandlers/bulkRemapTokens.ts
- src/types/AsyncMessages.ts
https://www.loom.com/share/bb6f715d45974f5f8d84de49bf4e5cc1
> apply user choice when rename token group

- src/app/components/MoreButton/MoreButton.test.tsx
- src/app/components/MoreButton/MoreButton.tsx
- src/app/components/TokenButton/TokenButtonContent.tsx
https://www.loom.com/share/529d0ae6409e4fc8b56fa12e1e6a3868
> 1340-add-shortcut-for-editing-a-token

- src/app/components/DownshiftInput/DownshiftInput.tsx
> sort name depends on string + number

- src/app/components/ColorTokenForm.tsx
- src/app/store/models/tokenState.test.ts
- src/utils/alias/getAliasValue.ts
- src/utils/modifyColor.ts
- src/utils/updateTokenPayloadToSingleToken.ts
https://www.loom.com/share/04988a5b2170431a93e4dc69f76cbd96
> 1569-color-modifier-allow-aliasing-and-math

- src/app/components/ExportProvider/SingleFileExport.test.tsx
- src/app/components/ExportProvider/SingleFileExport.tsx
- src/app/store/useTokens.test.tsx
- src/app/store/useTokens.tsx
- src/utils/__tests__/__snapshots__/convertTokensObjectToResolved.test.ts.snap
- src/utils/__tests__/convertTokensObjectToResolved.test.ts
- src/utils/convertToDefaultProperty.test.ts
- src/utils/convertToDefaultProperty.ts
- src/utils/convertTokens.test.ts
- src/utils/convertTokens.tsx
- src/utils/convertTokensObjectToResolved.ts
- src/utils/convertTokensToGroupedObject.ts
- src/utils/formatTokens.ts
- src/utils/types.d.ts
- token-transformer/README.md
- token-transformer/cli.js
- token-transformer/output/composition.json
@six7 You can review this again.
> add expandborder to token transformer

- src/utils/alias/__tests__/deepLinkingAlias.test.ts
- src/utils/alias/getAliasValue.ts
https://www.loom.com/share/c416851ba7884210920f2940467ebeee
> fix nested referece broking

- src/plugin/figmaTransforms/lineHeight.test.ts
- src/plugin/figmaTransforms/lineHeight.ts
https://user-images.githubusercontent.com/102773603/218662952-0fa4609d-ce1d-4f01-a90b-d901d01eaa3c.mp4
> 1045 ability to add line height token in rem units

- src/app/components/AddLicenseKey/AddLicenseKey.test.tsx
- src/app/components/AddLicenseKey/AddLicenseKey.tsx
- src/app/store/models/userState.ts
- src/mocks/handlers.ts
* The remove license key should be there even if the license key is invalid
* The add license key will be there only if theres no key added
* Fixed tests to reflect the new functionality
> 82 if the license key is invalid you cannot remove it

- flags.d.ts
- src/app/components/ColorTokenForm.tsx
git push --set-upstream origin 1620-move-color-modifiers-behind-pro-feature-flag
> add pro to color modifier

- src/app/components/BoxShadowInput.tsx
@six7 You can see it again.
https://www.loom.com/share/e0fbe664f55d48998961248f56ea8187
> 1567-issue-when-adding-shadows-in-reference-mode

- src/app/components/SecondScreenSync/index.tsx
* In some cases an infinite loop was caused, and the connection lost.
> Fix supabase subscribe issue

- src/app/components/EditTokenForm.tsx
- src/app/components/EditTokenFormModal.tsx
- src/app/store/models/tokenState.test.ts
- src/app/store/models/tokenState.tsx
- src/types/payloads/DuplicateTokenPayload.ts
https://www.loom.com/share/b31faf78475f4272a1610263a650df88
> duplicate token across sets

- src/app/components/MoreButton/MoreButton.tsx
https://www.loom.com/share/19fbfdf4eaf14b1d809e9db6bf5c7318
> fix applying token when click with cmd

- src/app/components/BorderTokenForm.tsx
- src/app/components/BoxShadowInput.tsx
- src/app/components/TypographyInput.tsx
- src/app/store/models/tokenState.test.ts
- src/constants/AliasRegex.ts
- src/utils/alias/__tests__/getAliasValue.test.ts
- src/utils/alias/getAliasValue.ts
- src/utils/findReferences.test.ts
- src/utils/findReferences.tsx
https://www.loom.com/share/462ec0d71c2244b7aeb4b497023fa7fa
> nest reference

- src/app/components/AppContainer/startupProcessSteps/pullTokensFactory.ts
- src/app/store/models/tokenState.tsx
- src/app/store/remoteTokens.tsx
- src/app/store/updateSources.tsx
- src/constants/SharedPluginDataKeys.ts
- src/figmaStorage/CollapsedTokenSetsProperty.ts
- src/figmaStorage/index.ts
- src/plugin/asyncMessageHandlers/update.ts
- src/plugin/node.ts
- src/types/AsyncMessages.ts
- src/utils/__tests__/startup.test.ts
- src/utils/figma/updateLocalTokensData.ts
https://www.loom.com/share/944be51a8a1e4cbf96fa82bd13d55dc4
> 1582-save-the-state-of-the-treeview-through-closeopen

- src/plugin/removeValuesFromNode.test.ts
- src/plugin/removeValuesFromNode.ts
https://user-images.githubusercontent.com/25951419/225872615-8cd7bc79-7be3-4f73-88ee-f167360e68a3.mp4
> 1606-text-decoration-none-not-applied

- src/config/properties.js
- src/config/tokenType.defs.json
- src/config/tokenTypes.js
- src/constants/Properties.ts
- src/constants/TokenTypes.ts
- src/plugin/__tests__/setValuesOnNode.test.ts
- src/plugin/removeValuesFromNode.test.ts
- src/plugin/removeValuesFromNode.ts
- src/plugin/setValuesOnNode.ts
- src/types/payloads/UpdateTokenPayload.ts
- src/types/tokens/EditTokenObject.ts
- src/types/tokens/SingleBooleanToken.ts
- src/types/tokens/SingleToken.ts
- src/types/tokens/index.ts
https://user-images.githubusercontent.com/25951419/226072060-2a503306-99b4-49d1-8fbd-a040aa1b2b4a.mp4
> add new boolean type token

- src/plugin/node.test.ts
- src/plugin/node.ts
https://user-images.githubusercontent.com/25951419/226546208-c0b25307-6542-4d1e-85e3-cec0cb37e256.mp4
> 1596-color-modifier-make-it-possible-document-the-modify-of-a-token

- src/plugin/tokenHelpers.test.ts
- token-transformer/modifier/$metadata.json
- token-transformer/modifier/$themes.json
- token-transformer/modifier/core.json
- token-transformer/modifier/theme/01-light.json
- token-transformer/modifier/theme/02-dark.json
- token-transformer/output/tokens-modifier.json
- token-transformer/package.json
- token-transformer/transform.test.js
> add color modifier test coverage

- src/plugin/setTextValuesOnTarget.ts
@six7 Just added try-catch so if possible we can merge without adding test coverage.
> 1634-uppercase-doesnt-work-when-i-use-it-through-the-typography

- src/plugin/renameStylesFromPlugin.test.ts
- src/plugin/renameStylesFromPlugin.ts
https://user-images.githubusercontent.com/25951419/227324092-40132eed-2d68-4ce1-88a7-2305d2b0b133.mp4
> 1685-problems-with-renaming-tokens-not-syncing-to-native-figma-styles

- src/storage/ADOTokenStorage.ts
https://user-images.githubusercontent.com/25951419/227830240-9285ad22-0926-4192-94db-08ad46dae912.mp4
> 1697-ado-on-initial-setup-the-tokensjson-file-is-not-created-resulting-in-an-error

- src/app/components/DownshiftInput/MentionInput.tsx
- src/app/components/EditTokenForm.test.tsx
- src/app/components/EditTokenForm.tsx
- src/app/components/Input.tsx
https://user-images.githubusercontent.com/25951419/228445256-61d2a07a-1de7-4826-8626-adf2f29b2930.mp4
> remove empty values in typography

- src/app/components/modals/BulkRemapModal.tsx
Uploading 20230330_220841.mp4…
> add option for bulk remap across document

- src/plugin/getFigmaDashPattern.ts
- src/plugin/setBorderValuesOnTarget.ts
https://user-images.githubusercontent.com/25951419/231309502-a536a2df-8b07-4cbc-be1b-bc8a681e9964.mp4
> add dash pattern based on border width

- catalog-info.yaml
- src/app/components/JSONEditor.tsx
- src/app/components/ManageThemesModal/ManageThemesModal.tsx
- webpack.config.js
Add support for our json schema for autocomplete and adds backstage config
> Json schema and backstage

- src/app/components/CompositionTokenForm.tsx
- src/app/components/SingleCompositionTokenContent.tsx
- src/app/components/SingleCompositionTokenForm.tsx
https://user-images.githubusercontent.com/25951419/231633239-1ba2730a-0cfc-43e1-835a-4b183f1b909c.mp4
> 1559 ability to reorder composition token values

- src/plugin/__tests__/updateColorStyles.test.ts
- src/plugin/__tests__/updateEffectStyles.test.ts
- src/plugin/updateColorStyles.ts
- src/plugin/updateEffectStyles.ts
- src/plugin/updateStyles.test.ts
- src/plugin/updateStyles.ts
- src/plugin/updateTextStyles.test.ts
- src/plugin/updateTextStyles.ts
- src/utils/getEffectStylesIdMap.ts
- src/utils/getPaintStylesIdMap.ts
- src/utils/getTextStylesIdMap.ts
https://user-images.githubusercontent.com/25951419/230179449-e3f5797f-34e5-4bbe-9c6d-6632eca18054.mp4
> 1058-allow-token-names-and-style-names-to-be-different-while-still-in-sync

- src/app/components/SingleBoxShadowInput.tsx
https://user-images.githubusercontent.com/25951419/234591026-df717255-f569-4589-bfd9-ff8ebabc9aff.mp4
> 1812-shadows-with-an-array-update-the-previewed-value-even-when-not-hitting-save

- src/app/store/models/tokenState.tsx
Uploading 20230426_110058.mp4…
> 1795-error-in-duplicating-and-removing-modifier-from-color-token

- .vscode/launch.json
- src/app/components/AddLicenseKey/AddLicenseKey.test.tsx
- src/app/components/AppContainer/__tests__/AppContainerIntegration.test.tsx
- src/app/components/ImportedTokensDialog.test.tsx
- src/app/components/OnboardingFlow.test.tsx
- src/app/store/models/effects/tokenState/removeStyleNamesFromThemes.ts
- src/app/store/models/effects/tokenState/renameStyleNamesToCurrentTheme.ts
- src/app/store/models/settings.tsx
- src/app/store/models/tokenState.test.ts
- src/app/store/models/tokenState.tsx
- src/app/store/providers/__tests__/genericVersioned.test.ts
- src/app/store/providers/generic/versionedStorage.ts
- src/app/store/providers/jsonbin.tsx
- src/app/store/remoteTokens.test.ts
- src/app/store/updateSources.tsx
- src/storage/GenericVersionedStorage.ts
- src/storage/JSONBinTokenStorage.ts
- src/storage/__tests__/GenericVersionedStorage.test.ts
- src/storage/__tests__/JSONBinTokenStorage.test.ts
- src/types/AsyncMessages.ts
- src/types/StorageType.ts
Addresses https://github.com/tokens-studio/figma-plugin/issues/1727
A lot of this was swallowing errors as well as not correctly setting `saveLastSyncedState` after saving
> fix issues with not throwing errors correctly

- src/plugin/node.ts
- src/plugin/removeValuesFromNode.test.ts
- src/plugin/removeValuesFromNode.ts
https://user-images.githubusercontent.com/25951419/234542810-7d85cf5b-b0f5-4866-b222-038a1d171fa2.mp4
> 1829 border token cant be applied to bottom left and right separate

- src/app/components/ChangeStateListingHeading.tsx
- src/app/components/ChangedStateList.tsx
- src/app/components/ChangedTokenItem.tsx
- src/app/components/PullDialog.tsx
- src/app/components/PushDialog.tsx
- src/app/components/PushJSON.tsx
- src/app/components/PushSettingForm.tsx
Fixes some styling issues with the new push / pull dialog
> fix: style pull dialog

- src/app/components/DownshiftInput/MentionInput.tsx
- src/app/components/EditTokenForm.tsx
- src/app/components/InspectorTokenSingle.tsx
https://user-images.githubusercontent.com/25951419/235627540-92c13c88-4438-4c45-9c21-96c019287848.mp4
> 1842 next branch hitting enter in a token value field now causes a multi line input instead of submitting

- src/app/components/AppContainer/startupProcessSteps/pullTokensFactory.ts
- webpack.config.js
Addresses https://github.com/tokens-studio/figma-plugin/issues/1839
> 1839 fix recovery shown on startup

- src/app/components/InspectSearchOptionDropdown.tsx
- src/app/components/Inspector.tsx
- src/app/components/ManageThemesModal/ManageThemesModal.tsx
- src/app/components/ManageThemesModal/ThemeListGroupHeader.tsx
- src/app/components/ManageThemesModal/ThemeListItemContent.tsx
- src/app/components/ManageThemesModal/TokenSetThemeItem.tsx
- src/app/components/Modal/Modal.tsx
- src/app/components/Modal/ModalFooter.tsx
- src/app/components/SingleCompositionTokenContent.tsx
- src/app/components/StyledDragger/StyledDragButton.tsx
- src/app/components/TokenSetItem/TokenSetItem.tsx
couple of style changes for the manage themes dialog
> fix: style changes themes

- cypress/support/mockEnv.js
- package.json
- script/release.sh
- src/app/components/ErrorMessage.tsx
- src/app/components/SyncSettings.tsx
- src/storage/GithubTokenStorage.ts
- src/storage/__tests__/GithubTokenStorage.test.ts
- tests/__mocks__/octokitRestMock.d.ts
- tests/__mocks__/octokitRestMock.js
- Fixes an issue where sometimes we wouldn't show all branches that are available in GitHub in the branch selector
- Fixes an issue with error messages in Figma's light theme
- Fixes an issue with sync provider icons in Figma's light theme
> Release 1.35.4

- src/app/store/models/reducers/tokenState/saveTheme.ts
https://user-images.githubusercontent.com/25951419/236714200-e47f720c-7bbc-452c-b2ea-343ef1293f77.mp4
> make theme to noGroup

- src/app/components/ThemeSelector/ThemeSelector.tsx
https://user-images.githubusercontent.com/25951419/237015916-6d9cb388-7d76-4435-89c0-0b911396f9c8.mp4
> 1613-if-the-themes-dropdown-is-long-make-it-scroll

- src/app/components/EditTokenForm.tsx
- src/app/components/TokenListing.tsx
https://github.com/tokens-studio/figma-plugin/assets/25951419/14d04560-dcc2-4996-abdd-810172b8e2da
> add # prefix to input value if the token is color token

- src/app/components/TokenGroup/TokenGroup.tsx
- src/app/components/TokenListing.tsx
https://github.com/tokens-studio/figma-plugin/assets/25951419/94bc18ff-6631-4f20-af09-3dd3c65fb77e
> 1772-when-using-custom-token-types-delete-token-group-doesnt-work

- src/app/store/useTokens.tsx
- src/plugin/updateStyles.ts
https://github.com/tokens-studio/figma-plugin/assets/25951419/9e490f7e-de45-48c2-a9a9-d89253d7435d
> 1612 when no styles were created due to ignore first part of token name for styles inform the user via notification

- src/app/components/ManageThemesModal/ThemeStyleManagementCategory.tsx
- src/app/components/ManageThemesModal/ThemeStyleManagementCategoryStyleEntry.tsx
- src/app/components/ManageThemesModal/ThemeStyleManagentForm.tsx
- src/app/store/models/reducers/tokenState/disconnectStyleFromTheme.ts
https://user-images.githubusercontent.com/25951419/236976372-aabee7cc-d21d-4dfb-8f89-1ac996da0f7d.mp4
> 1803 allow to select alldetach all styles in manage themes

- package-lock.json
- package.json
Turns out we just needed to update the deps
> Fix scroll bug

- src/app/components/DownshiftInput/MentionInput.tsx
https://github.com/tokens-studio/figma-plugin/assets/25951419/652b297f-0bdc-4316-9901-340ba5853880
> 1885-nextbeta-tokenpicker-closing-bracket-bug

- src/app/components/PushDialog.tsx
https://github.com/tokens-studio/figma-plugin/assets/25951419/3bbaf7c9-12bf-40bf-9ad8-1469212c6df1
> 1871-nextbeta-push-dialog-doesnt-push-on-changes-or-json-tab

- src/app/components/BorderTokenDownShiftInput.tsx
- src/app/components/BorderTokenForm.tsx
- src/app/components/BoxShadowInput.tsx
- src/app/components/ColorTokenForm.tsx
- src/app/components/CompositionTokenForm.tsx
- src/app/components/DownshiftInput/DownshiftInput.tsx
- src/app/components/DownshiftInput/MentionInput.tsx
- src/app/components/EditTokenForm.tsx
- src/app/components/InspectorTokenSingle.tsx
- src/app/components/SingleBoxShadowDownShiftInput.tsx
- src/app/components/SingleBoxShadowInput.tsx
- src/app/components/SingleCompositionTokenContent.tsx
- src/app/components/SingleCompositionTokenForm.tsx
- src/app/components/SingleTypographyDownShiftInput.tsx
- src/app/components/TypographyInput.tsx
https://github.com/tokens-studio/figma-plugin/assets/25951419/f39b98a6-bc08-4da5-99d6-45b4f8e63565
> 1886-nextbeta-pressing-enter-while-selecting-from-autocomplete-submits-token-form

- src/app/components/ThemeSelector/ThemeSelector.tsx
- src/stitches.config.ts
> themeSelector-theme-change

- package.json
- script/release.sh
- src/app/store/remoteTokens.tsx
- src/plugin/setTextValuesOnTarget.ts
fixes a few error captures that were unnecessary.
> fix: remove unnecessary error calls

- cypress/support/mockEnv.js
- src/app/components/AppContainer/__tests__/AppContainerIntegration.test.tsx
- src/storage/GithubTokenStorage.ts
- src/storage/__tests__/GithubTokenStorage.test.ts
Fixes the 1mb limit on a single file https://octokit.github.io/rest.js/v18#repos-get-content by swapping to getting a raw value.
This should work for smaller files as well
> Fixes the 1mb limit on a file by swapping to raw values

- src/plugin/setValuesOnVariable.ts
> 1975-color-modifiers-do-not-carry-across-to-figma-variables

- src/plugin/createLocalVariablesInPlugin.ts
This is for [this tickek](https://github.com/tokens-studio/figma-plugin-internals/issues/22)
https://github.com/tokens-studio/figma-plugin/assets/25951419/77312102-0da1-4033-ae7c-2a449bf02000
> 22-variables-when-using-create-variables-show-the-user-a-notify-when-it-was-successful-and-indicate-the-amount-of-variables-created

- src/app/components/ManageThemesModal/ThemeVariableManagement.tsx
- src/plugin/asyncMessageHandlers/resolveVariableInfo.ts
This one is for [this ticket](https://github.com/tokens-studio/figma-plugin-internals/issues/23)
https://github.com/tokens-studio/figma-plugin/assets/25951419/ad41dc6a-54db-42b7-87c0-56250aaa768d
> 23-variables-in-manage-themes-when-trying-to-detach-variables-we-do-not-seem-to-update-the-ui

- src/app/components/EditTokenForm.tsx
- src/app/store/models/effects/tokenState/index.ts
- src/app/store/models/effects/tokenState/removeVariableNamesFromThemes.ts
- src/app/store/models/effects/tokenState/renameVariableNamesToThemes.ts
- src/app/store/models/reducers/tokenState/index.ts
- src/app/store/models/reducers/tokenState/removeVariableNamesFromThemes.ts
- src/app/store/models/reducers/tokenState/renameVariableNamesToThemes.ts
- src/app/store/updateSources.tsx
- src/app/store/useManageTokens.tsx
- src/app/store/useTokens.tsx
- src/plugin/asyncMessageHandlers/index.ts
- src/plugin/asyncMessageHandlers/update.ts
- src/plugin/asyncMessageHandlers/updateVariables.ts
- src/plugin/controller.ts
- src/plugin/createLocalVariablesInPlugin.ts
- src/plugin/renameVariablesFromPlugin.ts
- src/plugin/setValuesOnVariable.ts
- src/plugin/syncVariables.ts
- src/plugin/updateVariables.ts
- src/plugin/updateVariablesFromPlugin.ts
- src/types/AsyncMessages.ts
- src/types/payloads/UpdateTokenVariablePayload.ts
For [this ticket](https://github.com/tokens-studio/figma-plugin-internals/issues/34)
https://github.com/tokens-studio/figma-plugin/assets/25951419/04668e3b-3e63-414b-8599-243bb0e9b157
> 34-variables-when-renaming-a-token-that-is-a-reference-to-another-token-we-do-not-update-the-reference

- src/plugin/setBorderColorValuesOnTarget.ts
- src/plugin/setValuesOnNode.ts
- src/utils/tryApplyColorVariableId.ts
- src/utils/tryApplyVariableId.ts
https://github.com/tokens-studio/figma-plugin/assets/25951419/6a001094-aab0-4d96-a5f1-91827efa79d3
> 1996 when working with variables bordercolor is applied as style instead of variable

- src/app/components/EditTokenForm.tsx
- src/plugin/setValuesOnVariable.ts
- src/plugin/updateVariablesFromPlugin.ts
- src/types/payloads/UpdateTokenVariablePayload.ts
https://github.com/tokens-studio/figma-plugin/assets/25951419/260f1563-177d-4998-86b4-4b8573ec3661
> 2015-variables-color-modifiers-strange-behaviour-on-saving-a-modified-color

- src/AsyncMessageChannel.ts
> fix: empty message ignore

- .github/workflows/release.yml
- src/app/components/AddLicenseKey/AddLicenseKey.tsx
- src/app/components/BorderTokenForm.tsx
- src/app/components/ChangedStateList.tsx
- src/app/components/ChangedTokenItem.tsx
- src/app/components/Changelog.tsx
- src/app/components/ColorTokenForm.tsx
- src/app/components/CompositionTokenForm.tsx
- src/app/components/EditTokenForm.tsx
- src/app/components/ImportedTokensDialog.tsx
- src/app/components/InspectorDebugView.tsx
- src/app/components/LoadingBar.tsx
- src/app/components/MultiSelectDropdown.tsx
- src/app/components/PushDialog.tsx
- src/app/components/RemConfiguration.tsx
- src/app/components/SingleBoxShadowInput.tsx
- src/app/components/SingleCompositionTokenForm.tsx
- src/app/components/StorageItemForm/JSONBinForm.tsx
- src/app/components/TokenGroup/TokenGroupHeading.tsx
- src/app/components/TokenListing.tsx
- src/app/components/TokenSetItem/TokenSetItem.tsx
- src/app/components/TypographyInput.tsx
- src/utils/uiSettings.ts
- Fix bug with translation hook being inconsistent
- Fix workflow to be environment scope
> RC feedback

- .github/workflows/release.yml
- CHANGELOG.md
> fix: release injection

- src/plugin/node.ts
https://github.com/tokens-studio/figma-plugin/assets/25951419/4b22b955-05ef-43c4-aab3-e87c2d5996a7
> 1932-using-border-token-in-composition-is-not-working-properly

- src/app/components/ManageThemesModal/ManageThemesModal.tsx
- src/utils/dragDropOrder/findOrderableTargetIndexesInThemeList.tsx
https://github.com/tokens-studio/figma-plugin/assets/25951419/5270c569-9b9c-473c-8174-712aea2e728e
> 1941-drag-and-dropping-themes-conceals-themes

- .github/workflows/nightly.yml
- src/app/components/StorageItemForm/GitForm.tsx
- src/app/components/StorageItemForm/URLForm.tsx
- src/i18n/index.ts
Fixes the missing translation keys in the url form 
Also fixes the issue with the nightly build tagging
Addresses #2048
> fix missing translation keys

- src/app/components/DownshiftInput/DownshiftInput.tsx
- src/app/components/TypographyInput.tsx
> 2051-auto-complete-broken-for-typography-tokens

- .changeset/unlucky-apples-eat.md
- src/app/components/ApplySelector.tsx
> Fixes Apply to document text

- .changeset/flat-onions-allow.md
- src/app/components/Footer.tsx
> Up sync frequency in background

- .github/workflows/release.yml
The content permission in the release needs to have write permission
> fix: release permissions

- CHANGELOG.md
- package.json
Versioning was incorrectly set to 1.37.7 instead of 1.37.6
> fix: incorrect changelog

- src/i18n/lang/en/errors.json
fixes https://github.com/tokens-studio/figma-plugin/issues/2102
> Fixes error message for when tokens share name with a group

- .changeset/wild-worms-divide.md
- manifest.json
- src/plugin/controller.ts
- src/plugin/performCodeGen.test.ts
- src/plugin/performCodeGen.ts
- tests/__mocks__/figmaMock.d.ts
- tests/__mocks__/figmaMock.js
This PR originated from https://github.com/tokens-studio/figma-plugin-devmode/pull/1 - but then realized we could just add it to the existing plugin quite easily.
Originally contributed by @tdesero - thanks a ton 🎉 
https://github.com/tokens-studio/figma-plugin/assets/4548309/22ba61df-e385-4fac-b9bb-c7439a7bf311
> Adds Dev Mode

- src/app/components/EditTokenForm.tsx
- src/app/components/TokensBottomBar.tsx
- src/app/store/remoteTokens.tsx
> add new metrics

- .changeset/chatty-kids-check.md
- src/storage/SupernovaTokenStorage.ts
- Add 2 more Supernova environments (demo and staging)
> Add 2 more environments for Supernova

- src/app/components/createTokenObj.tsx
https://github.com/tokens-studio/figma-plugin/assets/25951419/9305cfb3-7f7a-4a59-baf5-9e004c52a665
[This issue](https://github.com/tokens-studio/figma-plugin/issues/2224)
> 2224-typing-in-the-search-field-crashes-the-plugin

- src/plugin/setValuesOnVariable.ts
- src/plugin/updateVariablesFromPlugin.ts
- src/utils/alias/__tests__/checkCanReferenceVariable.test.ts
- src/utils/alias/checkCanReferenceVariable.tsx
https://github.com/tokens-studio/figma-plugin/assets/25951419/ffad2024-4e44-4f31-beef-54a0ec5ccae5
> 2059-calculated-values-are-not-respected-in-variables-1

- src/app/store/models/settings.tsx
Updated the default applyMode from PAGE to SELECTION.
> 2192-apply-to-setting-defaults-back-to-document-after-crash

- src/tokens/core.ts
https://github.com/tokens-studio/figma-plugin/assets/25951419/bd1f92f5-5540-44e5-9378-04b1c6a9fa24
> 1925-scrolling-down-the-dropdown-menu-also-scrolls-the-plugin-screen

- src/app/components/TokenFilter.tsx
https://github.com/tokens-studio/figma-plugin/assets/103296157/afad66d3-7370-449c-aab8-9a2ff6617b36
> 583-add-an-easy-way-to-clear-search-field01

- src/app/components/StorageItem.tsx
https://github.com/tokens-studio/figma-plugin/assets/103296157/0448e0bd-0091-41b3-b35e-d4a990cbe453
> 1817-removing-sync-provider-causes-the-plugin-to-throw-an-error-about-incorrect-credentials-on-boot

- src/app/components/DownshiftInput/DownshiftInput.tsx
https://github.com/tokens-studio/figma-plugin/assets/103296157/306cce5a-f6e4-46e3-b5c6-b8e01aa730d5
> 1759-typography-input-field-tooltip-direction

- .changeset/cold-glasses-stare.md
- src/app/components/DownshiftInput/mentions.css
> fixes suggestions input color

- .changeset/old-goats-hide.md
- src/app/components/MoreButton/MoreButton.test.tsx
- src/app/components/MoreButton/MoreButton.tsx
fixes https://github.com/tokens-studio/figma-plugin/issues/2151
> change windows shortcut

- .changeset/new-elephants-prove.md
- src/app/store/models/reducers/tokenState/setTokenData.ts
- src/app/store/models/tokenState.tsx
- src/app/store/providers/ado/ado.tsx
- src/app/store/providers/bitbucket/bitbucket.tsx
- src/app/store/providers/generic/versionedStorage.ts
- src/app/store/providers/github/github.tsx
- src/app/store/providers/gitlab/gitlab.tsx
- src/app/store/providers/jsonbin.tsx
- src/app/store/providers/url.tsx
- src/app/store/remoteTokens.tsx
https://github.com/tokens-studio/figma-plugin/assets/103296157/590916ac-42d7-4f63-9b2b-b95396e4588c
> Changing Branches Deselects all Previously Selected Themes

- .changeset/neat-tools-hammer.md
- src/app/components/DownshiftInput/mentions.css
- src/app/components/EditTokenForm.tsx
- src/app/store/models/reducers/__tests__/renameStyleIdsToTheme.test.ts
- src/app/store/models/reducers/__tests__/renameVariableNamesToThemes.test.ts
- src/app/store/models/reducers/tokenState/renameStyleIdsToCurrentTheme.ts
- src/app/store/models/reducers/tokenState/renameStyleNamesToCurrentTheme.ts
- src/app/store/models/reducers/tokenState/renameVariableNamesToThemes.ts
- src/app/store/useManageTokens.tsx
- src/app/store/useTokens.test.tsx
- src/app/store/useTokens.tsx
- src/plugin/asyncMessageHandlers/renameStyles.ts
- src/plugin/renameStylesFromPlugin.test.ts
- src/plugin/renameStylesFromPlugin.ts
- src/types/AsyncMessages.ts
https://github.com/tokens-studio/figma-plugin/assets/103296157/262ddee1-7d21-4cf5-b324-04f9facd069e
> 1821-cant-rename-stylesvariables-after-changing-the-parent-name-of-a-token-group

- .changeset/lazy-experts-switch.md
- src/app/store/models/reducers/tokenState/saveTheme.ts
https://github.com/tokens-studio/figma-plugin/assets/103296157/8f011893-9678-4a00-9c31-bd1325a4f037
> 1930-active-theme-disabled-upon-editing-and-saving

- .changeset/great-scissors-notice.md
- src/app/store/useTokens.test.tsx
- src/app/store/useTokens.tsx
https://github.com/tokens-studio/figma-plugin/assets/103296157/41b901f1-35cb-4b63-ae1f-66bd05c02965
> For-multi-value-number-or-dimension-or-spacing-or-sizing-tokens-we-should-skip-them

- .changeset/beige-radios-press.md
- src/app/store/useTokens.tsx
Fixes a breaking issue which caused data mutation and changed token values
> fix mutating data

- .changeset/tough-houses-juggle.md
- src/app/components/TokenGroup/TokenGroupHeading.tsx
- src/app/store/models/tokenState.tsx
- src/app/store/useManageTokens.tsx
- src/app/store/useTokens.test.tsx
- src/app/store/useTokens.tsx
- src/plugin/renameVariablesFromPlugin.ts
- src/types/tokens/TokenToRename.ts
- src/types/tokens/index.ts
https://github.com/tokens-studio/figma-plugin/assets/103296157/423cae0d-3718-4f53-8c84-2ae6ba0878ae
> Unusual remapping renaming behaviour

- .changeset/quick-birds-smell.md
- src/plugin/updatePluginDataAndNodes.test.ts
- src/plugin/updatePluginDataAndNodes.ts
https://github.com/tokens-studio/figma-plugin/assets/103296157/5278d16c-b8ff-48d6-a92a-d937004a9cb3
> 2353-unable-to-un-apply-tokens-on-multiple-layers-at-once

- .changeset/five-poets-trade.md
- package-lock.json
- packages/tokens-studio-for-figma/package-lock.json
- src/utils/alias/__tests__/getAliasValue.test.ts
- src/utils/color/mix.ts
- src/utils/convertModifiedColorToHex.test.ts
- src/utils/modifyColor.test.ts
Closes #2402 
The mix colormodifer ignored the colorspace option. This PR adds it.
> Add colorspace option to mix

- .changeset/fresh-yaks-film.md
- manifest.json
- src/app/hooks/usePropertiesForType.test.ts
- src/app/hooks/usePropertiesForType.ts
- src/constants/Properties.ts
- src/plugin/setValuesOnNode.ts
Closes #682  
Adds X and Y properties to number and dimension tokens
> Add x and y property

- packages/tokens-studio-for-figma/src/app/store/models/tokenState.tsx
- packages/tokens-studio-for-figma/src/app/store/providers/tokens-studio/tokensStudio.tsx
- packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/createTokenSetInTokensStudio.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/deleteTokenSetFromTokensStudio.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/duplicateTokenInTokensStudio.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/createTokenSetMutation.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/deleteTokenSetMutation.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/index.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/updateTokenSetMutation.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/index.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/updateTokenSetInTokensStudio.ts
Closes https://github.com/tokens-studio/studio-app/issues/792
Added support for updating data in Tokens Studio from the plugin:
- duplicate token in multiple token sets
- create token set
- rename token set
- delete token set
https://github.com/tokens-studio/figma-plugin/assets/19837930/24b37553-f547-4619-ae6d-204a8e904e8c
> [792] Tokens Studio - CUD for token sets and duplicate token

- packages/tokens-studio-for-figma/src/app/components/ApplySelector.tsx
- packages/tokens-studio-for-figma/src/app/components/Footer.tsx
- packages/tokens-studio-for-figma/src/app/components/Inspector.tsx
- packages/tokens-studio-for-figma/src/app/components/InspectorDebugView.tsx
- packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx
- packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/useExportThemesTab.tsx
- packages/tokens-studio-for-figma/src/app/components/Modal/Modal.tsx
- packages/tokens-studio-for-figma/src/app/components/OnboardingFlow.tsx
- packages/tokens-studio-for-figma/src/app/components/SettingsDropdown.tsx
- packages/tokens-studio-for-figma/src/app/components/StylesDropdown.tsx
- packages/tokens-studio-for-figma/src/app/components/SyncSettings.tsx
- packages/tokens-studio-for-figma/src/app/components/TokensBottomBar.tsx
- packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json
- packages/tokens-studio-for-figma/src/stitches.config.ts
- packages/tokens-studio-for-figma/src/utils/removeTokenId.ts
Fixes several 2.0 branch related issues
Fixes DTCG not being available for local storage sync
Fixes dropdown for importing styles and variables being missing
Fixes create themes button not doing anything (removed it, feels like we're better off without it here)
Adjusts apply selector size
should be all good. famous last words.
> fix release 139 issues

- packages/tokens-studio-for-figma/package.json
- packages/tokens-studio-for-figma/src/app/components/TokenFlowButton/index.tsx
- yarn.lock
The call to token flow was using axios to trigger the post to token flow, instead of requiring a package just for that let's use the native fetch
Try to launch tokenflow
> chore: remove axios

- .changeset/mighty-queens-yawn.md
- packages/tokens-studio-for-figma/src/app/store/useTokens.tsx
Closes https://github.com/tokens-studio/figma-plugin/issues/2553
> Change default for import dialog

- packages/tokens-studio-for-figma/src/app/components/Inspector.tsx
- packages/tokens-studio-for-figma/src/app/components/TokenSetItem/TokenSetItem.tsx
Fixes https://github.com/tokens-studio/figma-plugin/issues/2595 by importing the right components
> 2.0: fix checkboxes

- packages/tokens-studio-for-figma/src/app/components/Tokens.tsx
> Fix: #2597 [2.0] segmented control between json and list view needs state check

- packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/SingleThemeEntry.tsx
Closes https://github.com/tokens-studio/figma-plugin/issues/2577
Before:
After:
> [2.0]: ManageThemesModal / fix counts and styling

- packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx
- packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ThemeStyleManagementCategory.tsx
- packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/TokenSetThemeItem.tsx
- packages/tokens-studio-for-figma/src/app/components/MoreButton/MoreButton.tsx
- packages/tokens-studio-for-figma/src/app/components/Settings/Settings.tsx
- packages/tokens-studio-for-figma/src/app/components/ThemeSelector/ThemeSelector.tsx
Manage theme modal: adds small gap between actions and makes buttons variant default to indicate clickable elements
Privacy policy now has a target=blank to open a new web page
Manage themes dropdown now has a chevron right to indicate submenu
> 2.0: Small polish items

- packages/tokens-studio-for-figma/src/app/components/globalStyles.tsx
Fixes https://github.com/tokens-studio/figma-plugin/issues/2580
> fix: resize window is now possible in all modals

- packages/tokens-studio-for-figma/src/app/components/ApplySelector.tsx
- packages/tokens-studio-for-figma/src/app/components/BranchSelector.tsx
- packages/tokens-studio-for-figma/src/app/components/ExportProvider/MultiFilesExport.tsx
- packages/tokens-studio-for-figma/src/app/components/Modal/Modal.tsx
- packages/tokens-studio-for-figma/src/app/components/SettingsDropdown.tsx
- packages/tokens-studio-for-figma/src/app/components/SyncSettings.tsx
- packages/tokens-studio-for-figma/src/app/components/ThemeSelector/ThemeSelector.tsx
Fixes https://github.com/tokens-studio/figma-plugin/issues/2621
Adds the right css class names to have scrollbars appear
> 2.0: fixes scroll of various parts

- packages/tokens-studio-for-figma/src/app/store.ts
- packages/tokens-studio-for-figma/src/app/store/middlewares/index.ts
- packages/tokens-studio-for-figma/src/app/store/middlewares/tokenState.ts
- packages/tokens-studio-for-figma/src/app/store/providers/tokens-studio/tokensStudio.tsx
- packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/createTokenInTokensStudio.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/duplicateTokenInTokensStudio.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/createThemeGroupMutation.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/deleteThemeGroupMutation.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/index.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/updateThemeGroupMutation.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio/deleteTheme.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio/getThemeGroupsToUpdate.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio/index.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio/saveTheme.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio/updateThemeGroupName.ts
- packages/tokens-studio-for-figma/src/types/ThemeObject.ts
- packages/tokens-studio-for-figma/src/types/payloads/UpdateTokenPayload.ts
Closes https://github.com/tokens-studio/studio-app/issues/819
Adds support for operations on themes and groups:
- create theme group and theme
- update theme groups and themes
- delete theme groups and themes
- add variable ids and styles ids to themes
- update variable ids and styles ids for themes
> feat: [819] Add support for themes and groups operations

- packages/tokens-studio-for-figma/package.json
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/getProjectDataQuery.ts
> Upgrade sdk to 1.1.4

- packages/tokens-studio-for-figma/src/app/components/AnnotationBuilder.tsx
- packages/tokens-studio-for-figma/src/app/components/ConfirmDialog.tsx
- packages/tokens-studio-for-figma/src/app/components/DownshiftInput/DownshiftInput.tsx
- packages/tokens-studio-for-figma/src/app/components/DownshiftInput/StyledDownshiftInput.tsx
- packages/tokens-studio-for-figma/src/app/components/DownshiftInput/mentions.css
- packages/tokens-studio-for-figma/src/app/components/InspectorDebugView.tsx
- packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx
- packages/tokens-studio-for-figma/src/app/components/MultiSelectDropdown.tsx
- packages/tokens-studio-for-figma/src/app/components/TokenSetItem/TokenSetItem.tsx
- packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx
- packages/tokens-studio-for-figma/src/app/hooks/useConfirm.tsx
- packages/tokens-studio-for-figma/src/app/store/models/uiState.tsx
- packages/tokens-studio-for-figma/src/app/store/useManageTokens.tsx
Fixes a bunch of UI polish issues
Fixes https://github.com/tokens-studio/figma-plugin/issues/2646
Fixes https://github.com/tokens-studio/figma-plugin/issues/2584
Fixes https://github.com/tokens-studio/figma-plugin/issues/2647
Fixes https://github.com/tokens-studio/figma-plugin/issues/2650
Fixes https://github.com/tokens-studio/figma-plugin/issues/2682
Decided to introduce a variant: danger to our `useConfirm`
Decided to show disabled options in a disabled state when right clicking token set groups
Fixed a bunch of the visual issues like Portal and spacing of a few items
| Feature                | Before | After |
|------------------------|--------|-------|
| Inspect view           | ![](https://github.com/tokens-studio/figma-plugin/assets/4548309/6fde8e2f-4884-49b7-8166-7a5ea7090cab) | …
> 2.0: Polish UI bugs

- packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx
> 2.0 fix token submit enter

- .changeset/swift-spoons-sort.md
- packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/__tests__/bulkRemapTokens.test.ts
- packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/bulkRemapTokens.ts
This is just a rebase of https://github.com/tokens-studio/figma-plugin/pull/2511 to release-139. Merging as code is not mine and I'm merely approving.
> adds bulkremap support

- packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2763
Styles were created with transparent colors, this PR fixes this.
Adjusts the logic we had in setColorValuesOnTarget which was used when we create color styles. Basically we were just checking if the value is a reference, but we didnt check if that reference exists as a variable.
Changed it so that when the variable doesn't exist, we proceed with the token value.
Try to replicate the steps in the video.
> 2.0: fix style creation

- packages/tokens-studio-for-figma/package.json
- packages/tokens-studio-for-figma/src/app/components/AuthModal/index.tsx
- packages/tokens-studio-for-figma/src/app/components/DownshiftInput/MentionInput.tsx
- packages/tokens-studio-for-figma/src/app/components/DownshiftInput/mentions.css
- packages/tokens-studio-for-figma/src/app/components/Inspector.tsx
- packages/tokens-studio-for-figma/src/app/components/SecondScreen/index.tsx
- packages/tokens-studio-for-figma/src/app/components/SingleCompositionTokenForm.tsx
- packages/tokens-studio-for-figma/src/app/components/ThemeSelector/ThemeSelector.tsx
- yarn.lock
Various visual polish for 2.0 rc7
> 2.0: various polish

- packages/tokens-studio-for-figma/src/app/components/Modal/Modal.tsx
quick PR to revert the change that we did for the modal backdrop. lets make this change in the ds repo instead.
> fix modal backdrop

- packages/tokens-studio-for-figma/src/app/components/RemConfiguration.tsx
- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
- packages/tokens-studio-for-figma/src/i18n/lang/en/storage.json
- packages/tokens-studio-for-figma/src/i18n/lang/es/storage.json
- packages/tokens-studio-for-figma/src/i18n/lang/fr/storage.json
- packages/tokens-studio-for-figma/src/i18n/lang/hi/storage.json
- packages/tokens-studio-for-figma/src/i18n/lang/nl/storage.json
- packages/tokens-studio-for-figma/src/i18n/lang/zh/storage.json
Adds a teaser for Tokens Studio sync before showing the form values given we're still in early access
Default
On click "Already got access?"
If form is opened when values are present
(no teaser visible)
(also fixes some formatting issues in RemConfiguration)
> Polish tokens studio form

- packages/tokens-studio-for-figma/package.json
- packages/tokens-studio-for-figma/src/stitches.config.ts
- yarn.lock
adds lightFigma theme (will merge without approval due to release of rc8)
> add light figma theme

- packages/tokens-studio-for-figma/src/app/components/DownshiftInput/MentionInput.tsx
Precursor to https://github.com/tokens-studio/figma-plugin/pull/2923 that fixes the most important pieces: Selecting mentions
> fixes mentions input re-apply

- packages/tokens-studio-for-figma/src/app/store/useTokens.tsx
> Fix stuck load-bar when token sets are empty whilst creating styles

- packages/tokens-studio-for-figma/package.json
- yarn.lock
Fixes https://github.com/tokens-studio/figma-plugin/issues/2895
Fixes https://github.com/tokens-studio/figma-plugin/issues/2908
Fixes those issues by upgrading to the latest `tokens` package version
> Upgrade UI

- packages/tokens-studio-for-figma/src/app/components/TokenSetSelector.tsx
makes token set button no longer sticky
> revert new token set button sticky

- packages/tokens-studio-for-figma/package.json
- yarn.lock
upgrades `tokens` package to 0.1.8
> upgrade UI tokens

- packages/tokens-studio-for-figma/src/storage/BitbucketTokenStorage.ts
- packages/tokens-studio-for-figma/src/storage/__tests__/BitbucketTokenStorage.test.ts
Resolves https://github.com/tokens-studio/figma-plugin/issues/2997
> Fix bitbucket sync themes when pulling from a single json file

- packages/tokens-studio-for-figma/src/plugin/TokenValueRetriever.ts
> Fix raw value composition tokens

- packages/tokens-studio-for-figma/src/app/components/TokenTooltip/TokenTooltipContentValue.tsx
- packages/tokens-studio-for-figma/src/utils/is/isSingleBorderToken.ts
- packages/tokens-studio-for-figma/src/utils/is/isSingleBoxShadowToken.ts
- packages/tokens-studio-for-figma/src/utils/is/isSingleCompositionToken.ts
- packages/tokens-studio-for-figma/src/utils/is/isSingleTypographyToken.ts
> Fix resolved tokens preview in typo composition

- packages/tokens-studio-for-figma/src/app/components/AddLicenseKey/AddLicenseKey.tsx
> Fix license key padding

- packages/tokens-studio-for-figma/package.json
- yarn.lock
Upgrades UI package to fix the broken UI in bundled builds
> upgrade ui package to 0.9.0

- packages/tokens-studio-for-figma/package.json
- packages/tokens-studio-for-figma/src/app/store/models/reducers/__tests__/tokensStudio.test.ts
- packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/tokenFragment.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/utils/compositionFields.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/utils/index.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/utils/tokensStudioToToken.ts
- yarn.lock
This PR adds support for complex tokens aliases for both read and write.
Closes https://github.com/tokens-studio/studio-app/issues/1234
> Fix complex tokens for studio sync

- .changeset/calm-parrots-develop.md
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/getProjectDataQuery.ts
Raise the limit for tokens from 400 to 3000 when requesting data from Tokens Studio platform
> fix: Raise limit for tokens in Tokens Studio sync

- packages/tokens-studio-for-figma/src/app/components/ConvertToDTCGModal.tsx
> Fix dtcg link

- packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
fixes the env variable for ts sync
> fix ts sync env

- packages/tokens-studio-for-figma/src/config/default.json
Modifies preset file to round off font size calculations
[core.json](https://github.com/user-attachments/files/18828856/core.json)
> Update preset file

- packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/getProjectDataQuery.ts
Fixes https://github.com/tokens-studio/studio-app/issues/2152
> replace tokens with raw in GetProjectData Query

- .changeset/selfish-adults-allow.md
- packages/tokens-studio-for-figma/src/app/components/AppContainer/startupProcessSteps/saveStorageInformationFactory.ts
- packages/tokens-studio-for-figma/src/app/components/ProBadge.tsx
- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
- packages/tokens-studio-for-figma/src/app/hooks/useIsProUser.ts
- packages/tokens-studio-for-figma/src/app/store/models/userState.ts
- packages/tokens-studio-for-figma/src/selectors/tokensStudioPATSelector.ts
FIxes #3277 
- Remove your existing license key our plugin
- Add a tokens studio sync provider, with studio api key
- If the sync succeeds, the user will be upgraded to a `PRO` user immediately
> Once user adds a studio api key sync, he will be activated as pro user

- packages/tokens-studio-for-figma/src/plugin/__tests__/processTextStyleProperty.test.ts
- packages/tokens-studio-for-figma/src/plugin/processTextStyleProperty.ts
- packages/tokens-studio-for-figma/src/plugin/pullStyles.ts
this is a suggested changeset for `fix-typography-reference-on-style-imports` in https://github.com/tokens-studio/figma-plugin/pull/3305
There's a lot of duplicate code in that PR - this one cleans that up.
> Suggested changeset: DRY for font size import

- packages/tokens-studio-for-figma/src/app/components/ConvertToDTCGModal.tsx
- packages/tokens-studio-for-figma/src/app/components/InspectorMultiView.tsx
- packages/tokens-studio-for-figma/src/app/components/Settings/Settings.tsx
- packages/tokens-studio-for-figma/src/app/components/StartScreen.tsx
- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/ADOForm.tsx
- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/BitbucketForm.tsx
- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/GenericVersioned.tsx
- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/JSONBinForm.tsx
- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/SupernovaForm.tsx
- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/URLForm.tsx
- packages/tokens-studio-for-figma/src/app/components/TokenSetSelector.tsx
The docs links have been updated and so the old ones causes lot of broken analytics, this PR fixes it.
> fix updated docs link

- packages/tokens-studio-for-figma/src/app/components/Footer.tsx
display size indicator only on local storage
> display size indicator only on local storage

- packages/tokens-studio-for-figma/src/app/hooks/useStorageSizeWarning.tsx
- packages/tokens-studio-for-figma/src/hooks/__tests__/useStorageSizeWarning.test.ts
- packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json
- packages/tokens-studio-for-figma/src/plugin/node.ts
Updates the text displayed on the modal of the storage warning.
> Update modal text in storage size warning

- .changeset/tidy-pans-roll.md
- packages/tokens-studio-for-figma/src/app/components/AppContainer/startupProcessSteps/pullTokensFactory.ts
- packages/tokens-studio-for-figma/src/app/components/TokenSetTree.tsx
- packages/tokens-studio-for-figma/src/figmaStorage/__tests__/ClientStorageCleanup.test.ts
- packages/tokens-studio-for-figma/src/figmaStorage/__tests__/ThemesProperty.test.ts
- packages/tokens-studio-for-figma/src/figmaStorage/__tests__/ValuesProperty.test.ts
- packages/tokens-studio-for-figma/src/plugin/figmaTransforms/gradients.test.ts
Closes #3363 
This PR makes changes in PullTokensFactory to ensure that the plugin first checks if there is remote storage and no local changes need to be recovered, and it would fetch the API credentials when the plugin loads, and if the credentials are correct, it would simply load the tokens from the remote storage.
- Add a remote sync provider, like GitHub, load tokens.
- Restart the plugin to see if you encounter a credentials' issue
> Fix sync providers load

- .changeset/swift-suns-juggle.md
- packages/tokens-studio-for-figma/src/app/store/providers/tokens-studio/tokensStudio.tsx
- packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
> update error messages on studio sync

- packages/tokens-studio-for-figma/src/app/components/PresetProvider/FilePreset.tsx
> disable upload of multi file upload for non-pro users

- .changeset/calm-kiwis-impress.md
> Add changeset for 3425

- .changeset/sour-cobras-flow.md
> add changeset

- packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
- packages/tokens-studio-for-figma/src/app/store/models/reducers/__tests__/tokensStudio.test.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/StudioConfigurationService.test.ts
- packages/tokens-studio-for-figma/src/storage/tokensStudio/StudioConfigurationService.ts
Closes #3499  
This PR updates the default base URL(when no URL is provided) for studio sync from app.tokens.studio to app.prod.tokens.studio, since we have migrated from the old infra
- Create a tokens studio sync
- Keep default URL empty
- Check if sync is working as expected
> update default base url to app.prod.tokens.studio
