package.json, src/app/components/EditTokenForm.tsx, src/app/components/Input.tsx, src/app/components/NewGroupForm.tsx, src/app/components/TokenButton.tsx, src/app/components/TokenData.tsx, src/app/components/TokenListing.tsx, src/app/components/Tokens.tsx, src/app/components/renderKeyValue.tsx, src/app/components/utils.tsx, src/app/store/TokenContext.tsx, src/config/default.json, src/plugin/controller.ts, src/plugin/node.ts, src/plugin/styles.ts
This PR does multiple things:
- All tokens are now stored under a `value` prop of the Token.
- Reading old "non-value" style Tokens is still possible, editing them via UI will however create a token with that `value` prop.
- Descriptions can now be added to color styles and typography styles. Should expand that later to all tokens, as mentioned in #11
- Prepares a schema-like structure for tokens to prepare for custom UI handlers such as a color input mentioned in #6
I realize this could make the JSON output less useful to some (who may want a simple JSON structure and not a structure that stores token's values under a `value` property, however we should strive to store more data on each token so this is the only way to go, as well as being more compliant to (potential standards)
=> Read value key in tokens

package.json, src/app/components/Initiator.tsx, src/plugin/updateNode.ts
Fixes a bug reported for typography and text tokens when settings these directly on nodes
=> fixes #97: setting typography and text tokens directly on nodes

package.json, src/plugin/updateColorStyles.ts
Fixes comparison behaviour when old Figma style names with a space before / after delimiter are used, e.g.
`Volcano / 1` vs `Volcano/1`
=> fixes #140

src/plugin/figmaTransforms/generic.test.ts, src/plugin/figmaTransforms/generic.ts, src/plugin/helpers.ts, src/plugin/updateNode.ts
Currently the plugin doesn't support zero `0` values for tokens, the check `if (values.opacity)` for example skips the update because `0 === false` and then it won't update the styles.
I've updated the checks to `typeof prop !== 'undefined'` so it also works for 0 values and added an extra value check for properties that don't allow 0 values in Figma (ie. width, height, border width, …) and convert the 0 to 0.001.
This way I can set my opacity to 0 or hide elements.
What do you think?
=> Fixing zero values

src/plugin/tokenHelpers.ts
We currently were only evaluating math if there is at least one alias present in the project, which doesn't make any sense.
This PR fixes that.
=> resolves #192 - fix math when no aliases present

src/config/tokenTypes.js
Moved the blur key to between y and spread. If the edit token modal is pulling this index order to generate the fields, it will allow the user to input values in the same sequence as [CSS syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow#values) of "box-shadow: h-offset v-offset blur spread color;". This will also match the tab order of Figma's drop shadow values.
=> Reordering boxShadow values

.gitignore, src/plugin/pluginData.ts
This contribution introduces storing information about tokens used for specific layers in shared plugins space, so other plugins would use it.
Developers need to know, where to use which token. One of possibilities to solve this is to let them inspect tokens in Figma. This however creates risk of corruption of Design Tokens, for example by mistakenly changing their structure, or values.
That's why I created this dead simple inspector plugin (https://github.com/jhajduk-sage/figma-tokens-inspector) for tokens applied with Figma Tokens plugin. To make it work, design tokens information are needed to be stored in shared 'tokens' space.
I decided to add `setSharedlugnData` next to `setPluginData` (and not instead of) to be sure, that any accidental changes to the shared plugin data won't crash …
=> Share tokens with other plugins

src/app/components/EditTokenForm.tsx, src/app/store/models/tokenState.test.ts, src/app/store/models/tokenState.tsx, src/app/store/useTokens.tsx, src/plugin/tokenHelpers.ts, src/utils/aliases.tsx, src/utils/checkIfAlias.tsx, src/utils/findReferences.test.ts, src/utils/findReferences.tsx
Before, when you renamed a token that was being referenced, nothing would change and references would break.
With this PR, any reference to that token will be changed to the new reference. It will also change the alias style to `{name}`, because this will be the preferred way to declare aliases from now on (much safer).
Also, this PR adds checks to editing tokens that names cannot contain spaces.
=> renaming tokens now replaces references

cypress/integration/tokens.spec.js, src/app/components/TokenListing.tsx
Fixes bad UX by expanding all token groups when it shouldnt
Resolves #295
=> fixes #295

cypress/integration/tokens.spec.js, package.json, src/app/components/MoreButton.tsx, src/app/components/TokenButton.tsx, src/app/components/TokenListing.tsx, src/app/components/TokenTooltip.tsx, src/app/components/utils.test.ts, src/app/components/utils.tsx, src/config/properties.js, src/config/tokenTypes.js, src/plugin/figmaTransforms/colors.test.ts, src/plugin/figmaTransforms/colors.ts, src/plugin/figmaTransforms/textCase.test.ts, src/plugin/figmaTransforms/textCase.ts, src/plugin/figmaTransforms/textDecoration.test.ts, src/plugin/figmaTransforms/textDecoration.ts, src/plugin/helpers.ts, src/plugin/node.ts, src/plugin/pullStyles.test.ts, src/plugin/pullStyles.ts, src/plugin/setTextValuesOnTarget.test.ts, src/plugin/setTextValuesOnTarget.ts, src/plugin/setValuesOnNode.test.ts, src/plugin/setValuesOnNode.ts, src/plugin/tokenHelpers.test.ts, src/plugin/tokenHelpers.ts, src/utils/aliases.test.ts, src/utils/aliases.tsx, types/propertyTypes.ts
- Added textCase and textDecoration tokens as own tokens and as part of typography tokens - fixes #95 
- Fixes calculation of deep nested aliases especially when using rgba() and calc inside of them
- Fixes token buttons not having enough contrast when using hsla colors - fixes #309
- Fixes token categories always re-opening when adding/editing tokens - fixes #295 
- Fixes ability to remove Documentation Tokens from a layer
- Fixes Documentation token isActive state
=> Release 68

package.json, src/app/store/models/tokenState.test.ts, src/app/store/models/tokenState.tsx
This PR fixes a bug that would mess with array tokens (boxShadow for now) when renaming any token
=> Fix renaming tokens side-effects with arrays

package.json, src/app/components/createTokenObj.tsx, src/plugin/tokenHelpers.ts, src/utils/__snapshots__/convertTokensObjectToResolved.test.ts.snap, src/utils/convertTokens.tsx, src/utils/convertTokensObjectToResolved.test.ts, src/utils/convertTokensObjectToResolved.ts, src/utils/convertTokensToGroupedObject.ts, src/utils/test/github/input.json, src/utils/test/github/output.json, src/utils/transform.ts, src/utils/types.d.ts, token-transformer/README.md, token-transformer/index.js, token-transformer/input.json, token-transformer/output.json, webpack-transform.config.js, yarn.lock
Currently the **token-transformer** CLI automatically expands typography types to:
```
"typographyName": {
"fontFamily": {
"value": "Roboto"
},
"fontSize": {
"value": 18
}
}
```
For style-dictionary compatibility it would be easier to have the following format (especially for custom formats):
```
"typographyName": {
"type": "typography",
"value": {
"fontFamily": "Roboto",
"fontSize": 18
}
}
```
so we can use the **type** to group/filter typographies together.
This PR adds:
* yargs set-up for token-transformer inputs & validation
* possibility to add options for transformations (here I introduced expandTypography so users can opt-out of this auto expansion)
=> feat: options for token-transformer & expandTypography option for style-dictionary compatibility

src/app/components/TokenTooltip.tsx
Fixes line heights being shown twice, letterspacing wasn't visible and spaces were seemingly wrong.
=> Fix tooltips lineHeight and letterSpacing

src/utils/__snapshots__/convertTokensObjectToResolved.test.ts.snap, src/utils/convertTokensObjectToResolved.test.ts, src/utils/convertTokensObjectToResolved.ts, src/utils/convertTokensToGroupedObject.ts, src/utils/types.d.ts, token-transformer/index.js
This PR adds the option `--preserveRawValue` to `token-transformer` which does as it suggests... preserves the `rawValue` field in the token output. This value is very useful when theming because it preserves the context of what a given value referenced which can be useful in custom formatters.
As a use-case example, image you had this token config
```js
colors: {
base: {
green: {
'500': {
value: '#48d597',
type: 'color',
},
},
},
},
main: {
theme: {
accent: {
"1": {
value: "{base.green.500}",
type: "color"
}
}
},
content: {
accent: {
default: {
value: "{theme.accent.1}",
type: "color"
},
}
}
}
```
It's fairly clear from looking at the config that there's a relationship between `content-accent`, `theme-accent-1`, and `base-green-500`. If you're building a theming setup, preserving that …
=> Add the ability to preserve rawValue on token transform

src/utils/convertTokensToGroupedObject.ts, src/utils/formatTokens.test.ts, src/utils/formatTokens.ts, token-transformer/CHANGELOG.md, token-transformer/package.json
Before, with expandTypography set to true we'd get these tokens:
```
"base": {
"fontFamily": {
"value": "Inter",
},
"fontWeight": {
"value": "Regular",
},
"lineHeight": {
"value": "AUTO",
},
"fontSize": {
"value": 18,
},
"letterSpacing": {
"value": "0%",
},
"paragraphSpacing": {
"value": 0,
},
"textDecoration": {
"value": "none",
},
"textCase": {
"value": "none",
}
```
After this PR, we add the key as a type, so users could work with that in style dictionary.
```
"base": {
"fontFamily": {
"value": "Inter",
"type": "fontFamily"
},
"fontWeight": {
"value": "Regular",
"type": "fontWeight"
},
"lineHeight": {
"value": "AUTO",
"type": "lineHeight"
},
"fontSize": {
"value": 18,
"type": "fontSize"
},
"letterSpacing": {
"value": "0%",
"type": "letterSpacing"
},
"paragraphSpacing": {
"value": 0, …
```
=> [token-transformer]: Adds type to each item when expandTypography is true

src/app/components/EditTokenForm.tsx
=> Change token form validation to not allow creating a token that has the name of another token group

package.json, src/plugin/setValuesOnNode.ts
Fixes a bug that was introduced in V89 where we expected type: boxShadow to be passed but turns out we didnt 🤷‍♂️
fixes #567
=> Fix box shadows

package.json, src/plugin/setTextValuesOnTarget.ts
Fixes a bug that prevented users form using numerical font weights.
For example, a user that had `Museo Sans` that had a font weight of `500` could not use that combination. As Figma expects a string for `fontWeight`, but we returned `fontWeight` as we received it, in that case a number.
=> Fix numerical font weights

package.json, src/utils/math/__tests__/checkAndEvaluateMath.test.ts, src/utils/math/checkAndEvaluateMath.ts, yarn.lock
This allows expressions with units to be interpreted, which in turn solves the issue of not being able to use tokens with units in aliases. For instance, this will now work:
```
t1 = 10px
t2 = {t1} * 2
```
All the hard work is done by the `post-calc-at-parser` package by @ota-meshi, so most of the credit should go to them.
=> Add ability to use units in math expressions

src/app/components/TokenTooltip/SingleShadowValueDisplay.tsx, src/app/components/TokenTooltip/SingleTypograhpyValueDisplay.tsx, src/app/components/TokenTooltip/TokenTooltipContent.tsx, src/app/components/TokenTooltip/TokenTooltipContentValue.tsx
In our token listing performance effort we introduced a regression which caused tokens that used an alias to no longer show the alias, instead we only showed the resolved value.
Fixes https://github.com/six7/figma-tokens/issues/718
This PR reintroduces this.
We should still add tests for tooltips in a followup.
=> fix: token tooltip is missing alias value

webpack.config.js
This broke due to the webpack 5 upgrade.
=> FT-177 fix:watch command

src/app/components/TokenGroupHeading.tsx
Fixes a bug we introduced in the `next` branch where we added a gray border to token group headings, also fixes a few issues with the modal and eslint warnings.
=> Fix token heading display issue

.eslintrc.js, .vscode/extensions.json
This rule disallows some types such as `Object`, `object`, `{}`, etc... these are considered too vague and should not be used.
In this commit I also added eslint as a workspace recommendation for VSCode.
=> fix: eslint no object

src/storage/GithubTokenStorage.ts, src/storage/__tests__/GithubTokenStorage.test.ts
fixes setting collaborator permissions correctly when a user is part of an organization and has read-only mode set. github returns a 404 if you query permissions for a read only user, no data at all.
for user-based projects (where there are no permissions, but only collaborator or not) the user wouldn't even have access to the project.
=> FT-261 Fix read only on github

package.json, src/app/components/DownshiftInput/DownShiftInput.test.tsx, src/app/components/DownshiftInput/DownshiftInput.tsx, src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx, src/app/components/TokenSetSelector.tsx, src/app/hooks/useIsGitMultiFileEnabled.ts, src/app/store/models/tokenState.tsx, src/app/store/providers/ado/ado.tsx, src/app/store/providers/github/github.tsx, src/app/store/providers/gitlab/gitlab.tsx, src/app/store/providers/jsonbin.tsx, src/app/store/remoteTokens.test.ts, src/app/store/remoteTokens.tsx, src/storage/ADOTokenStorage.ts, src/storage/GitlabTokenStorage.ts, src/storage/__tests__/ADOTokenStorage.test.ts, src/storage/schemas/multiFileSchema.ts, src/utils/tokenset/tokenSetListToTree.ts
- Fixes a bug with duplicating token sets which caused them to be empty
- Fixes autocomplete for chinese inputs
- Adds test coverage for ADO
- Fixes subfolder issue for GitLab. Fixes #912
- Fixes multi file sync for ADO. Fixes #879
=> Release 111

.github/workflows/node.js.yml
Changes the test-coverage tests to update the same comment and introduces afterSwitchCommand which runs a yarn install after switching to base branch
=> fix coverage action same comment

package.json, src/app/hooks/useIsGitMultiFileEnabled.ts
Free users should be able to see token sets stored on a multi file sync as a tree, just like Pro users.
Before:
After:
=> fix: token sets show as list for free users even when using multi file sync

src/plugin/figmaUtils/getShadowBehindNodeFromEffect.test.ts, src/plugin/figmaUtils/getShadowBehindNodeFromEffect.ts, src/plugin/setEffectValuesOnTarget.test.ts, src/plugin/setEffectValuesOnTarget.ts
This PR introduces behavior that respects the layer / effect styles setting of `Show behind transparent areas`.
To try:
- Create a shadow token (with multiple layers using `Drop Shadow type`).
- Creatye styles
- Change the `Show behind transparent areas` setting in the Figma Styles / properties panel.
- Hit Update in the plugin and notice that the setting in the Style / properties panel didn't change.
Previous behavior: We always set that setting to `true`.
=> fix: respect setting of shadow behind node for effects

token-transformer/package.json
This change provides npm package pages to display reference links to GitHub repositories.
I learned about Token Transformer from [here](https://docs.tokens.studio/sync/github#7-how-to-use-tokens-stored-in-github-in-development) in the documentation and wanted to read the source code to learn more about its behavior.
However, I could not find it by googling and it took me a while to realize that it is located in a subdirectory of figma-tokens.
Therefore, I thought it would be easier for others to reference if a link was posted on the npm page.
=> docs(token-transformer): add repository field to package.json

package.json, src/app/components/ExportProvider/MultiFilesExport.tsx, src/app/components/ExportProvider/SingleFileExport.tsx, src/app/components/PresetProvider/DefaultPreset.tsx, src/app/components/PresetProvider/FilePreset.tsx, src/app/store/providers/ado/ado.tsx, src/app/store/providers/github/github.tsx, src/app/store/providers/gitlab/gitlab.tsx
Changes behaviour introduced in 114 for single file sort where we no longer respected the order of keys in the JSON. This does not fix the underlying problem that we so far do not respect the $metadata property in the json, I created https://github.com/six7/figma-tokens/issues/1162 to tackle that.
This PR changes it so if no $metadata is present (all the time currently), we use the order of keys in the JSON (behaviour pre-114)
=> fix sort for single file

src/app/components/TokenTooltip/SingleTypographyValueDisplay.tsx, src/app/components/TokenTooltip/TokenTooltipContentValue.tsx, src/types/CompositionTokenProperty.ts, src/types/tokens/SingleTypographyToken.ts, src/types/values/TokenTypographyValue.ts, src/utils/alias/getAliasValue.ts, src/utils/getValueWithReferences.ts, src/utils/is/isSingleTypographyValue.ts
Followup to #696 changing a misspelled type
=> fix spelling of typography value

src/app/store/providers/jsonbin.tsx, src/storage/GithubTokenStorage.ts, src/storage/__tests__/GithubTokenStorage.test.ts
Fixes #1170 as reported by Zach
=> fix: root directory sync issue

token-transformer/index.js
Currently token-transformer crashes when there are other files present (such as for example a `.DS_Store` file). This mitigates this, but there may be a better solution.
=> filter the list of token files to be transformed when using multifile

src/app/store/models/reducers/__tests__/assignStyleIdsToTheme.test.ts, src/app/store/models/reducers/tokenState/assignStyleIdsToCurrentTheme.ts, src/app/store/models/reducers/tokenState/assignStyleIdsToTheme.ts
This PR fixes a bug with `Create styles` which would detach any existing styles to our $themes object.
In `assignStyleIdsToTheme` I spread the existing `$figmaStyleReferences` before we spread the new object.
https://user-images.githubusercontent.com/4548309/185566427-7aaa3918-c470-47a3-938a-c414e6e70d25.mp4
https://user-images.githubusercontent.com/4548309/185566418-b7f8a48e-39e1-41bf-84fa-0b2cd48aea8f.mp4
=> Fixes Create styles removing previously attached styles

src/app/components/TokenListing.tsx
Sometimes users want to use custom types of tokens, they can do so by specifying this in the JSON by just adding something custom to the "type" field. The plugin respects that, and will show that type as the category name.
However, when you edit that token in the UI, we overwrite that token type and reset it to "other".
After fixing: Token type is kept as it was.
=> 1202-when-editing-a-token-of-a-custom-type-dont-overwrite-with-other

src/app/components/InspectorTokenSingle.tsx
When remapping a token, if we type $ and select a token from a list doesn't work.
Before fixing: 
Start to type: $
and then select "gray" from the list but doesn't work.
Right now: it works.
=> 841-auto-complete-in-token-picker-on-inspect-tab-does-not-work-correctly

src/app/store/models/reducers/tokenState/setTokenData.ts
After pushing to a repo, the plugin doesn't remember the tokenset you were on and shows the tokenset on top of the list.
After fixing: tokenset is kept after syncing with remote storage(github, gitlab, etc)
=> 1068-after-pushing-to-a-repo-the-plugin-doesnt-remember-the-tokenset-you-were-on-and-shows-the-tokenset-on-top-of-the-list

src/app/components/TokenButton/TokenButton.tsx
Documentation Token in Composition token doesn't work
.
=> 1065-documentation-tokens-doesnt-work-within-the-composition

src/app/components/AppContainer/startupProcessSteps/savePluginDataFactory.ts, src/app/store/models/settings.tsx
Fixed two issue.
https://github.com/six7/figma-tokens/issues/1223
https://github.com/six7/figma-tokens/issues/1224
The plugin seems to reset the window size when the user has
1. Changed window size
2. Then restarted the plugin
3. Then - without changing window size - changing Deep inspect
Notice how the plugin then resets the window size.
We seem to have caused a regression with Deep inspect:
To reproduce:
1. Activate deep inspect
2. Restart the plugin
3. Select a layer
4. Go to Inspect
5. Notice how even though it says Deep inspect is on, it only shows values of that current layer, not of children.
6. Turn Deep inspect off and on again
Notice that it now works
After fixing: Plugin keeps the window size and all children tokens are displayed after restarting the plugin.
=> 1224 plugin seems to reset window size when using deep inspect

src/app/components/DownshiftInput/DownShiftInput.test.tsx, src/app/components/DownshiftInput/DownshiftInput.tsx, src/utils/is/__tests__/isDocumentationType.test.ts, src/utils/is/isDocumentationType.ts
When trying to remap in the Inspect and the token you're trying to remap is on either of the Documentation properties (tokenName, value, rawValue, description) the modal that appears to give you suggestions doesn't show anythng.
After fixing: It shows all tokens when type is documentation type
=> 1125 suggestion dropdown doesnt appear for documentation tokens while changing to another token on the inspect tab

src/app/components/ResolvedTypograhpyValueDisplay.tsx
When you reference a semantic typography token that doesn't have a value for all three of the following tokens → textCase, paragraphSpacing and textDecoration, it doesn't keep the order or basically ignores empty fields.
=> 1188-typograhy-token-→-ignoresreorders-key-value-for-textcase-paragraphspacing-textdecoration

src/plugin/figmaTransforms/fontWeight.ts, src/plugin/helpers.test.ts, src/plugin/helpers.ts, src/plugin/pullStyles.ts, src/plugin/setTextValuesOnTarget.test.ts, src/plugin/setTextValuesOnTarget.ts, src/plugin/setValuesOnNode.ts
We can't set fontWeight with a number between 100 to 900 which is the most common way to set it.
After fixing:
In Figma, there is a match rule between font family and font-weight, so every font weight doesn't work to every font family.
To test this, we can use `Montserrat` fontfamily which support all font weights from 100 to 900.
=> 807 cannot set a number fontweight in typography

src/app/store/models/tokenState.test.ts, src/app/store/models/tokenState.tsx
Unsaved local changes are lost when update button is clicked and plugin is re-opened
=> 1216 update button loses unsaved local changes

src/app/components/Initiator.tsx, src/app/components/InspectorMultiView.tsx, src/app/components/modals/BulkRemapModal.tsx, src/app/store/useTokens.test.tsx, src/app/store/useTokens.tsx, src/plugin/asyncMessageHandlers/__tests__/bulkRemapTokens.test.ts, src/plugin/asyncMessageHandlers/bulkRemapTokens.ts, src/plugin/asyncMessageHandlers/index.ts, src/plugin/asyncMessageHandlers/remapTokens.ts, src/plugin/controller.ts, src/types/AsyncMessages.ts
Users can remap several tokens at once.
Users can click bulk remap button in Inspect Tab and type part of the old name and new name.
Then all tokens are remaped with new name
=> 1135 allow bulk remap

src/app/components/AppContainer/startupProcessSteps/__tests__/getLdFlagsFactory.test.ts, src/app/store/providers/ado/ado.tsx, src/app/store/providers/bitbucket/bitbucket.tsx, src/app/store/providers/github/github.tsx, src/app/store/providers/gitlab/gitlab.tsx, src/app/store/remoteTokens.test.ts, src/constants/ErrorMessages.ts, src/storage/GitTokenStorage.ts, src/storage/__tests__/GithubTokenStorage.test.ts
Currently when you try to save a Github repo as a free user, but have a multi-file setup (no .json in filepath), there is strange behaviour and you get stuck in a push-loop (see attached video).
Add a clear error that indicates the problem of this behaviour
=> 1169 add error handling when a free user tries to save a repo with a multi file setup pro feature

src/app/components/TokenSetSelector.tsx
Make it possible to add folders/groups for sets. This should work the same as the feature in Multi File:
Simply renam token sets to have a folder path, eg folder/set-1 , folder/set-2
=> 1077-support-folder-structure-for-non-multi-file

src/app/components/EditTokenForm.tsx
Fixes #1244 
Changes `Input` to `Textarea` in `EditTokenForm` so that we can show and create multiline text descriptions.
https://user-images.githubusercontent.com/4548309/189426693-7cbe436a-2939-428e-ae12-760f67570ad6.mp4
=> Allow multiline description in token

src/app/components/TokenGroup/TokenGroup.test.tsx, src/app/components/TokenGroup/TokenGroupHeading.tsx
Renaming a token group seems to have a strange side-effect: It collapses the token group while renaming.
Expected: Don't collapse groups while renaming
https://www.loom.com/share/eeb6db0d63884bd6b5e1a0be6ad1457e
=> 1278-120-rc1-renaming-token-groups-causes-them-to-collapse

src/storage/GithubTokenStorage.ts, src/storage/__tests__/GithubTokenStorage.test.ts
Sometimes when using Git storage removing a token set fails. It seems to be connected to the name of the set, as it's not happening all the time.
https://www.loom.com/share/a383c5d6b04e42b1aede02bd60f91846
=> 1275-removing-token-sets-sometimes-fails

src/plugin/asyncMessageHandlers/bulkRemapTokens.ts
This PR changes bulk remap to no longer scan the currently selected updateMode but instead always takes selection (because that's what should happen in Inspect)
Also changes implementation so the `match` doesn't just have to startWith the word, but can be anywhere.
=> Changes bulk remap to selection and includes

src/app/components/MoreButton/MoreButton.tsx
fixes #1374
we previously passed the token value into the function evaluating if it's a multi-value token (e.g. `8px 16px 16px 4px` for spacing or borderRadius). Now we pass in the resolved function.
=> Fix tokens containing spaces having disabled context menu

package.json, script/release.sh, src/app/components/AppContainer/__tests__/AppContainerIntegration.test.tsx, src/app/components/AppContainer/startupProcessSteps/__tests__/pullTokensFactory.test.ts, src/app/components/AppContainer/startupProcessSteps/pullTokensFactory.ts, src/app/components/DownshiftInput/DownshiftInput.tsx, src/app/components/Footer.tsx, src/app/components/StartScreen.tsx, src/app/components/StorageItemForm/ADOForm.tsx, src/app/components/StorageItemForm/BitbucketForm.tsx, src/app/components/StorageItemForm/GitForm.tsx, src/app/components/SyncSettings.test.tsx, src/app/components/modals/EditStorageItemModal.tsx, src/utils/alias/getAliasValue.ts, src/utils/transformProviderName.tsx
Fixes an edge case bug where users who had an empty tokens file were shown the `Enter credentials` message.
Also cleans up some of the UI copy to make it a bit clearer what's going on.
=> fix credentials start message

src/app/components/Initiator.tsx, src/plugin/__tests__/notifiers.test.ts, src/plugin/notifiers.ts, src/plugin/setTextValuesOnTarget.ts, src/types/messages.tsx
Fixes https://github.com/six7/figma-tokens/issues/1396
Shows a more prominent error when font weight/family combination can't be applied.
Also adds error tracking so we're aware of which combinations don't work.
=> Improve error setting font weight/family

src/app/components/ApplySelector.tsx, src/app/components/Button/Button.tsx, src/app/components/Button/StyledButton.tsx, src/app/components/Checkbox.tsx, src/app/components/EditTokenForm.tsx, src/app/components/Input.tsx, src/app/components/InspectorMultiView.tsx, src/app/components/InspectorTokenSingle.tsx, src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx, src/app/components/ManageThemesModal/ManageThemesModal.tsx, src/app/components/OnboardingExplainer.tsx, src/app/components/PushDialog.tsx, src/app/components/Settings/Settings.tsx, src/app/components/StorageItemForm/ADOForm.tsx, src/app/components/StorageItemForm/GitForm.tsx, src/app/components/StorageItemForm/JSONBinForm.tsx, src/app/components/StorageItemForm/URLForm.tsx, src/app/components/SyncSettings.test.tsx, src/app/components/TabButton/TabButton.tsx, src/app/components/TokenGroup/TokenGroupHeading.tsx, src/app/components/TokenSetSelector.tsx, src/app/components/modals/BulkRemapModal.tsx, src/app/components/modals/CreateStorageItemModal.tsx, src/stitches.config.ts
Mostly cleans up the UI
- to make use of the Modal Header props
- remove `Update remote` when not using JSONbin as it was only applicable there
- Adds a Danger button variant
- Makes the `Delete` button in Themes use Danger
- Integrates autofocus prop on Input so we can utilize that more generic
- Fixes the sizing of buttons on credential forms
=> Autofocus improvements

src/app/hooks/usePropertiesForType.test.ts, src/app/hooks/usePropertiesForType.ts, src/constants/Properties.ts, src/plugin/helpers.ts, src/plugin/setBackgroundBlurOnTarget.test.ts, src/plugin/setBackgroundBlurOnTarget.ts, src/plugin/setValuesOnNode.ts
Fixes https://github.com/six7/figma-tokens/issues/1129
Fixes https://github.com/six7/figma-tokens/issues/1291
Introduces an option to `dimension` type tokens that allow users to target `background blur`.
=> Background blur

src/app/components/LoadingBar.tsx
Small nit: typo on the loading bar messaging.
=> typo: Fixed typo on loading bar message

src/storage/GitlabTokenStorage.ts, src/storage/__tests__/GitlabTokenStorage.test.ts
We're currently blocked from using the plugin because after connecting to our private GitLab server the plugin refuses to let us write any changes (even though it was able to create a commit with the new json file).
After some debugging we found that the GitLab API was returning a 404 error when trying to fetch the member data for the project. This is because our GitLab repository inherits the members from another group and it doesn't have any direct members itself. To get all the members including the inherited ones you need to fetch another endpoint.
By including the `includeInherited` option in the calls to `GroupMembers` and `ProjectMembers` from the `@gitbeaker/browser` package this issue will be resolved for us as it will hit the correct endpoint. According to GitLab's own …
=> GitLab sync: Include inherited members when checking for write permissions

package.json, script/release.sh, src/app/components/InspectorTokenSingle.tsx, src/app/store/useTokens.test.tsx, src/app/store/useTokens.tsx, src/plugin/NodeManager.ts, src/plugin/SharedDataHandler.test.ts, src/plugin/SharedDataHandler.ts, src/plugin/__tests__/setValuesOnNode.test.ts, src/plugin/asyncMessageHandlers/bulkRemapTokens.ts, src/plugin/figmaUtils/styleUtils.ts, src/plugin/pluginData.test.tsx, src/plugin/pluginData.ts, src/plugin/removeValuesFromNode.test.ts, src/plugin/setValuesOnNode.ts, src/storage/GitlabTokenStorage.ts, src/storage/__tests__/GitlabTokenStorage.test.ts, src/types/AsyncMessages.ts
- Fixes an issue with GitLab group credentials not being inherited. Thanks @robin-ambachtsheer
- Fixes an issue with renaming token groups where user choice was sometimes ignored and only applied on selection
- Fixes an issue with `none` value tokens sometimes causing tokens not being applied
- Adds support for the `none` keyword in token values
- Removed an older migration that should speed up performance by a bit
=> Release 134

src/app/components/TokenSetItem/TokenSetItem.tsx
We use URL Sync, and with URL sync editing of the tokens is disabled inside Tokens Studio. However, currently, this also hides away the "Treat as source" functionality, which has nothing to do with editing the tokens, rather it's a special checked state of the tokenset. Since you can check/uncheck the tokensets even when you can't edit, I believe you should also be able to treat the tokenset as source.
PS. Sorry for jumping directly to a PR, seemed like a small enough change so we can discuss directly here if necessary?
PPS. There are some unrelated autoformatting changes in here, I can undo them manually, if necessary, but it's a bit cumbersome so I did not do that right now. Not sure what is going on with the prettier config in this repo, does not seem to be enforced.
=> fix: allow "treat as source" without edit rights

src/app/components/PushDialog.test.tsx, src/app/components/PushDialog.tsx
Fixes calling `onConfirm` inside `PushDialog` for Supernova integration, which has no `commitMessage` or `branch`. This was lost after last changes to `PushDialog`.
=> fix: push dialog for Supernova onConfirm should be called

src/app/store/remoteTokens.tsx
This https://github.com/tokens-studio/figma-plugin/blob/87d272b9bbf5b27eddaf4038ec7cc18261253c5c/src/app/store/remoteTokens.tsx#L453 is currently causing an issue.
It is possible that the context value is not provided or null from remote storage, etc.
This is currently causing unnecessary errors in Sentry despite it not causing a crash to the plugin
=> fix: flooding errors

src/storage/__tests__/FileTokenStorage.test.ts, src/storage/schemas/themeObjectSchema.ts
This should fix the issue identified in #1981 where theme group metadata is ignored when loading tokens from storage.
=> Fix theme groups not being loaded (#1981)

src/storage/__tests__/UrlTokenStorage.test.ts, src/storage/schemas/multiFileSchema.ts
Likely fixes #1927. Ran into it while trying to generate multi theme variables for Figma :) I guess the zod schema validation just stripped unknown properties.
Note: Originally this PR fixed URL sync as well, but a fix for that was merged separately in #1982.
=> fix: respect theme groups from multi file import

src/utils/validateLicense.ts
The prior usage of Sentry setUser could result in non anonymized sessions that could be associated with user details like names. This should be removed
=> Ensure no additional telemetry could be used to associate user sessions

src/app/store/updateSources.tsx
Addresses #2028 
We are currently just exposing more surface area for the unnecessary configuration of a storage provider. If a provider does  not need this hook they should be able to ignore it and rather opt in if necessary
=> Add better tracking for error event

.changeset/proud-cheetahs-float.md, src/app/components/PushDialog.tsx
Fixes a bug that was introduced with i18n
Before:
After:
=> fix sync tabs

.changeset/breezy-trainers-hug.md, package-lock.json, package.json, src/plugin/NodeManager.ts, src/plugin/__tests__/setValuesOnNode.test.ts, src/plugin/controller.ts, src/plugin/getAppliedVariablesFromNode.ts, src/plugin/node.ts, src/plugin/sendDocumentChange.ts, src/plugin/setValuesOnNode.test.ts, src/plugin/setValuesOnNode.ts, tests/__mocks__/figmaMock.js
Removed migrateTokens call. This was something we added to migrate border tokens to borderColor tokens. I's likely ok to remove this, it's been around 6 months since we introduced the border tokens or more. This was responsible for a lot of calls to Updating plugin data... which caused everything to be rather slow.
I added a few checks to document changes. This is basically responsible for checking if other users are changing something to applied tokens, and then we would invalidate and re-fetch those nodes. However, it also ran on all document changes, including internal ones and from the user. I removed this, and it should lead to less calls and faster execution time.
Also fixes a major issue that caused us to iterate over all variable references _on every node_ resulting in poor …
=> Perf fixes

.changeset/breezy-spiders-cross.md, src/storage/SupernovaTokenStorage.ts
- Fixes order sync when push, then pull from Supernova.
https://github.com/tokens-studio/figma-plugin/assets/729374/15317825-7225-4a84-98e4-76143851135e
https://github.com/tokens-studio/figma-plugin/assets/729374/eebb1318-0329-4466-8993-940a2e10e73b
=> fix: SupernovaTokenStorage should persist $metadata

.changeset/moody-chairs-eat.md, src/plugin/asyncMessageHandlers/__tests__/bulkRemapTokens.test.ts, src/plugin/asyncMessageHandlers/__tests__/remapTokens.test.ts, src/plugin/asyncMessageHandlers/__tests__/removeTokensByValue.test.ts, src/plugin/asyncMessageHandlers/bulkRemapTokens.ts, src/plugin/asyncMessageHandlers/remapTokens.ts, src/plugin/asyncMessageHandlers/removeTokensByValue.ts, src/plugin/asyncMessageHandlers/setNodeData.ts, src/plugin/asyncMessageHandlers/setNoneValuesOnNode.ts, src/plugin/asyncMessageHandlers/update.ts, src/plugin/node.test.ts, src/plugin/node.ts, src/plugin/pluginData.test.tsx, src/plugin/pluginData.ts, src/plugin/updateNodes.ts, src/plugin/updatePluginData.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2129
Removes `updatePluginData` calls from the `update` call, as we only used that for migration purposes. We would still do that when users apply tokens or remap tokens, but we won't do anymore on every Apply to.. call
* `src/plugin/asyncMessageHandlers/update.ts`: The `updatePluginData` function is no longer used in the `update.ts` file, so the import statement and call to the function have been removed. (remove `updatePluginData` references in `update.ts`)
https://github.com/tokens-studio/figma-plugin/assets/4548309/57759166-42be-4d1e-878a-89ecc63301f7
=> fix apply performance

.changeset/curly-ravens-prove.md, .changeset/rare-cups-join.md, .changeset/young-kangaroos-brake.md, src/app/components/ConfirmDialog.tsx, src/app/components/EditTokenForm.tsx, src/app/components/Input.tsx, src/app/components/TokenTooltip/TokenTooltip.tsx, src/app/store/useTokens.tsx
Fixes https://github.com/tokens-studio/figma-plugin/issues/2031
Fixes https://github.com/tokens-studio/figma-plugin/issues/2097
Fixes https://github.com/tokens-studio/figma-plugin/issues/1799
This set of changes includes improvements to the user experience and state management, as well as bug fixes. The `ConfirmDialog` and `Input` components were updated to ensure immediate focus on the input element after rendering. The `useTokens` module and `EditTokenForm` component now store the last used update mode when renaming tokens, improving state management and UI. Two bug fixes were also included, related to issues when renaming tokens or token groups.
* `src/app/components/Input.tsx`: `setTimeout` function removed and `focus()` called directly on `htmlInputRef.current` to ensure immediate …
=> fix rename/updatemode and input issues

manifest.json
fixes https://github.com/tokens-studio/planning/issues/81
adds an entry to manifest.json for networkAccess of the plugin
=> add network access to manifest

.changeset/big-bottles-share.md, src/app/components/ColorTokenForm.tsx, src/app/components/DownshiftInput/mentions.css, src/app/components/ResolvingLoader/ResolvingLoader.tsx, src/app/components/SecondScreen/index.tsx, src/app/components/inspector/TokenNodes.tsx, src/plugin/updateNodes.ts
fixes an issue where we're not applying variables correctly when the theme had a missing variable reference
plus fixes an issue with wrong color tokens being used in manage themes
=> fixes variable resolution

src/app/store/useTokens.tsx
fixes an issue with statExtractor expecting an async return value
=> fix stat extractor error

.changeset/orange-boxes-thank.md, src/plugin/setBorderColorValuesOnTarget.ts, src/plugin/setValuesOnNode.ts, src/plugin/updateNodes.ts, src/types/RawVariableReferenceMap.ts, src/utils/tryApplyColorVariableId.ts, src/utils/tryApplyVariableId.ts
Adjusts how we resolve variable references from Figma by doing it on demand + caching it instead of getting all upfront
=> fix variables perf

.changeset/rare-seals-pump.md, src/plugin/setValuesOnNode.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2182
Fixes https://github.com/tokens-studio/figma-plugin/issues/2209
This change to `src/plugin/setValuesOnNode.ts` excludes instances from sizing property checks in the `setValuesOnNode` function, ensuring they only apply to autolayout frames or their direct children, and not instances which would throw an error.
=> fixes minwidth instance overrides

.changeset/six-berries-exist.md, src/utils/__tests__/mergeTokenGroups.test.ts, src/utils/tokenHelpers.ts
This fixes an issue where we did merge token sets in a wrong way. Previously, we'd merge tokens itself if they were of type `object`, but we didn't check specifically if it's an array. In the case of an array, merging is the wrong thing, we need to just replace it. This caused some tokens to not get any value if there was another set that had the same token (e.g. box shadows)
This pull request to the codebase improves the functionality and testing of the `mergeTokenGroups` function and fixes a bug related to shadow tokens with array values not being properly defined.
* `src/utils/__tests__/mergeTokenGroups.test.ts`: Updated test file to include new box shadow tokens and test their functionality with array values and multiple token sets. (<a …
=> fix: box shadow array values

.changeset/invisible-children.md, src/plugin/controller.ts
Removes the flag to skip invisible instance children given we no longer use a cache this now allows users to use boolean tokens on instances. Perf hit isnt an issue as we only operate on nodes that have pluginData stored.
=> remove skip inv instance children

src/plugin/createLocalVariablesInPlugin.ts
Fixed the bug where the variable collections are created 2 times in the epic branch.
In the epic branch, 2 collections are created.
Fixed so that there will be only one collection.
=> Fix/When we create the variable, collections are created 2 times

flags.d.ts, src/app/components/Settings/Settings.tsx
Hides the `id storage` feature behind a feature flag so it's not exposed to all users. We'll need to keep tweaking this one in a future iteration for it to be useful.
=> hide storage behind flag

.changeset/famous-flies-cover.md, src/plugin/getAppliedStylesFromNode.ts, src/plugin/removeValuesFromNode.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2205
The bug was basically caused by us trying to read effect values on a style, and expected those to be only of type `dropShadow` or `innerShadow` - however styles can also contain backgroundblur, which doesnt share the same object schema, causing an error when trying to parse those colors.
Changed it so that we only show styles which are of type shadow
=> Fix inspect being unresponsive

.changeset/happy-penguins-work.md, src/app/components/DownshiftInput/StyledDownshiftInput.tsx, src/app/components/DownshiftInput/mentions.css
Fixes our `Mentions` input to have a proper focus bg again.
Before
After
=> fix mentions input color

.changeset/great-taxis-grow.md, src/plugin/__tests__/setValuesOnNode.test.ts, src/plugin/setValuesOnNode.test.ts, src/plugin/setValuesOnNode.ts, src/utils/is/isPartOfInstance.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2270
This pull request includes changes to improve the functionality of a Figma plugin. The most important changes include adding a new function to check if a node is part of an instance, and updating a file to include a patch version for a dependency that fixes an issue with min width tokens in instances.
Main code changes:
* <a href="diffhunk://#diff-4ff7114e0f959bb00bfb7f861178407900b5158b1b2baab191f38be35e281970R33">`src/plugin/setValuesOnNode.ts`</a>: The `setValuesOnNode` function now checks if a node is part of an instance before applying min/max width/height values, using the `isPartOfInstance` function. <a href="diffhunk://#diff-4ff7114e0f959bb00bfb7f861178407900b5158b1b2baab191f38be35e281970R33">[1]</a> <a …
=> fix minwidth on instance children

.changeset/curvy-laws-attend.md, src/plugin/node.ts
This pull request includes changes to the `mapValuesToTokens` function in `src/plugin/node.ts` to modify the way descriptions and modifiers are added to tokens. 
* <a href="diffhunk://#diff-d2f51661f1da6b8ef9b60d8b500bad2293d880dccf9bea47ac00df746a8183e5R72-R81">`src/plugin/node.ts`</a>: Updated `mapValuesToTokens` function to modify the way descriptions and modifiers are added to tokens. <a href="diffhunk://#diff-d2f51661f1da6b8ef9b60d8b500bad2293d880dccf9bea47ac00df746a8183e5R72-R81">[1]</a> <a href="diffhunk://#diff-d2f51661f1da6b8ef9b60d8b500bad2293d880dccf9bea47ac00df746a8183e5L58-R58">[2]</a>
=> fix: documentation tokens

.changeset/selfish-lobsters-flash.md, src/app/components/InspectorMultiView.tsx, src/app/components/Settings/Settings.tsx, src/app/components/TokenSetSelector.tsx
This pull request updates URLs in several components to point to a new domain, `docs.tokens.studio`, instead of the old domain, `docs.figmatokens.com`. A
* `src/app/components/Settings/Settings.tsx`: Updated `onboardingData` object's `url` property to point to a new URL in `docs.tokens.studio` domain. (Ff9d8573L3R3)
* `src/app/components/InspectorMultiView.tsx`: Updated `onboardingData` object's `url` property to point to a new URL in `docs.tokens.studio` domain. (Ff4d8573L3R3)
* `src/app/components/TokenSetSelector.tsx`: Updated `onboardingData` object's `url` property to point to a new URL in `docs.tokens.studio` domain. (Ff8d8573L3R3)
=> fix onboarding links

.changeset/dirty-otters-notice.md, src/app/components/EditTokenForm.tsx, src/plugin/setValuesOnVariable.ts
https://github.com/tokens-studio/figma-plugin/assets/103296157/654ca965-b444-4c8a-9081-8cc6c51350b5
Closes https://github.com/tokens-studio/figma-plugin/issues/2081
=> Carry-over-token-descriptions-to-variable-descriptions

.changeset/selfish-buttons-guess.md, package-lock.json, src/app/components/InspectorResolvedToken.tsx, src/app/components/InspectorTokenSingle.tsx, src/app/components/TokenTooltip/TokenTooltipContent.tsx
https://github.com/tokens-studio/figma-plugin/assets/103296157/918a9caf-9e9c-4b80-9f50-aaa8358a0273
Closes https://github.com/tokens-studio/figma-plugin/issues/2124
=> 2124-show-token-values-in-inspect

.changeset/new-beers-visit.md, src/constants/AliasRegex.ts, src/utils/TokenResolver.test.ts, src/utils/TokenResolver.ts
Closes https://github.com/tokens-studio/figma-plugin/issues/2311
This pull request adds support for nested references to the `TokenResolver` utility, allowing for more complex references to be resolved. The most important changes include adding support for nested references in the `TokenResolver` class, updating the `TokenResolver.test.ts` file to test the new functionality, and updating the `AliasRegex` constant in `AliasRegex.ts` to match nested references.
Main changes:
* <a href="diffhunk://#diff-b4809e6851ac3bf8ff55467e9606b901d782180f05572177646b5b87641099e8R127-R159">`src/utils/TokenResolver.ts`</a>: Added support for nested references in `TokenResolver` class by resolving them using a while loop until there are no more matches.
* <a …
=> Reintroduce support for nested references

.changeset/sweet-walls-prove.md, src/app/store/models/settings.tsx, src/app/store/models/tokenState.tsx
Brings back the updateOnChange behavior when editing a token.
- If the user has the setting for update on change AND - their apply mode is set to page or selection
When: tokens are edited, update the nodes on either the page or their selection.
=> Feat/ reintroduce update on change

svgo.config.js
Fixes an issue on `main` with svgo's new config
Before
After
=> Update svgo.config.js to preserve removeViewBox

.changeset/spicy-scissors-sparkle.md, src/config/tokenType.defs.json
Current: Font size is after line-height 
Problem: Line-height is often dependent on font-size, so it would help to first set the font-size and then the line-height. 
Solution: Change the font-size input field position in the Typography composite token modal. 
PS: this is my first ever contribution to an open-source project, please be gentle when looking at naming conventions for branches/commits
=> Change font-size input field position in Typography composite token modal 

.changeset/tough-ways-do.md, packages/tokens-studio-for-figma/package.json, packages/tokens-studio-for-figma/src/plugin/__tests__/setValuesOnNode.test.ts, packages/tokens-studio-for-figma/src/plugin/setBorderValuesOnTarget.ts, packages/tokens-studio-for-figma/src/plugin/setValuesOnNode.ts, yarn.lock
Fixes https://github.com/tokens-studio/figma-plugin/issues/2414
Figma recently added support for binding variables to stroke weight and opacity (among others). This PR adds support for that.
Integrates our already used `tryApplyVariableId` to the stroke weight and opacity properties.
Create a dimension token, right click it and set `border width` to any of the properties. Make sure that that dimension token exists as a variable
Merging into `release-139` as the next major release.
=> Adds support for stroke weight and opacity variable binding

.changeset/slimy-files-reply.md, packages/tokens-studio-for-figma/src/app/components/AppContainer/startupProcessSteps/__tests__/pullTokensFactory.test.ts, packages/tokens-studio-for-figma/src/app/components/ImportedTokensDialog.test.tsx, packages/tokens-studio-for-figma/src/app/components/Initiator.test.tsx, packages/tokens-studio-for-figma/src/app/store/models/tokenState.test.ts, packages/tokens-studio-for-figma/src/types/payloads/DuplicateTokenPayload.ts, packages/tokens-studio-for-figma/src/types/payloads/UpdateTokenVariablePayload.ts, packages/tokens-studio-for-figma/src/types/tokens/SingleGenericToken.ts, packages/tokens-studio-for-figma/src/utils/addIdPropertyToTokens.ts, packages/tokens-studio-for-figma/src/utils/removeTokenId.ts, packages/tokens-studio-for-figma/src/utils/updateTokenPayloadToSingleToken.ts
We falsely stored the `id` property of tokens in the `$extensions` object, instead of properly placing it in the `$extensions` / `studio.tokens` property. This PR fixes that.
Tests were updated
=> Fix id location

packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
Studio sync was not working in our 2.0 branch, and it seems to have been caused (after we fixed some of the api key bugs) by the `createdAt` set metadata we queried. Removing that seems to have fixed the problem.
=> fix studio sync by removing metadata createdAt for set

.changeset/large-cows-guess.md, packages/tokens-studio-for-figma/src/app/components/ErrorFallback/ErrorFallback.tsx
Previously when errors occured the plugin wouldnt display the error boundary correctly, which we seem to have introduced somewhere along the way. This PR fixes that.
Remove hooks from the Error boundary which seems to fix the issue.
=> Fix issue with error boundary and UI error messages

packages/tokens-studio-for-figma/cypress/e2e/manage-themes.cy.js, packages/tokens-studio-for-figma/cypress/e2e/themes.cy.js, packages/tokens-studio-for-figma/src/app/components/ImportedTokensDialog.test.tsx, packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/SingleThemeEntry.tsx, packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/TokenSetThemeItem.tsx, packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/__tests__/SingleThemeEntry.test.tsx, packages/tokens-studio-for-figma/src/app/components/Modal/Modal.tsx, packages/tokens-studio-for-figma/src/app/components/Settings/Settings.test.tsx, packages/tokens-studio-for-figma/src/app/components/ToolsDropdown.tsx, packages/tokens-studio-for-figma/src/app/components/__tests__/TokenBottomBar.test.tsx, yarn.lock
Fixes failing tests on `release-139` as well as the incorrect modal styling
=> 2.0: fix tests and modals

.changeset/smart-countries-repair.md, packages/tokens-studio-for-figma/src/app/components/MoreButton/MoreButton.tsx
Fixes #2514
Users were able to cmd+click a token to reach the edit token form even if they didnt have edit rights
Adds the editProhibited condition to the cmd+click check
=> 2.0: fix cmd click

.changeset/small-coats-reflect.md, packages/tokens-studio-for-figma/src/app/components/TokenSetSelector.tsx
Fixes https://github.com/tokens-studio/figma-plugin/issues/2500
When creating a new token set, we should switch to that new set after creation.
Calls setActiveTokenSet after creation so that we switch to it
=> 2.0: on set create, put focus on new set

.changeset/chatty-turkeys-explain.md, packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx
When try to duplicate token to another token set with same name, there is a error alert 'Token names must be unique'.
Closes #2165 
Resolved to duplicate token to other token sets with same name.
Updated `EditTokenForm.tsx` and added a condition whether the `activeTokenSet` is included in `selectedItems` (token sets which user wants to duplicate the token to) list.
https://github.com/tokens-studio/figma-plugin/assets/103296157/f1af8a8f-d613-4517-8d2e-77a721fb92a5
=> 2165 duplicating a token to another set displays error 1

.changeset/proud-eels-change.md, src/storage/SupernovaTokenStorage.ts
Supernova released a new app with a different URL. Customers pasting new Supernova URL are not able to sync tokens.
Adds support for parsing new Supernova URL.
=> Fix parsing Supernova new app URL

.changeset/fuzzy-flies-fry.md, packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx
User can't edit token to add nested levels.
Closes #2386 
This PR gives ability to users to add nested levels to a token.
The current implementation has a if condition to check the new token name starts with one of resolved tokens name to check if token share the same name with group name which is a block to add nested levels.
This PR added a new condition here to check whether the user action is `create` or `edit` token.
https://github.com/tokens-studio/figma-plugin/assets/103296157/f2a98cdd-a053-4487-bbea-ca493ff3c733
=> 2386 ability to edit tokens to add nested levels

.changeset/fair-seals-type.md, packages/tokens-studio-for-figma/package.json, yarn.lock
We want figma plugin to hit production environment
It updates SDK which is responsible for make api call
Try to sync with production project. Test before merge since SDK is updated from 1.0.0 to 1.1.2
=> updated SDK to use prod environment

packages/tokens-studio-for-figma/package.json, packages/tokens-studio-for-figma/src/stitches.config.ts, yarn.lock
Changes styling of dark figma to be closer to Figma again (neutral grays)
Import the newly created darkFigmaTheme from tokens-studio/tokens
=> Introduce dark figma theme

.changeset/late-planes-buy.md, packages/tokens-studio-for-figma/src/app/hooks/useReferenceTokenType.ts
Closes https://github.com/tokens-studio/figma-plugin/issues/2528
Adds number and dimension token types to a couple of typography suggested types
=> Add number/dimension token types to suggestions for typography tokens

packages/tokens-studio-for-figma/src/app/components/AddLicenseKey/AddLicenseKey.test.tsx, packages/tokens-studio-for-figma/src/app/store/models/userState.ts
Closes https://github.com/tokens-studio/figma-plugin/issues/2548
Adds email address to licnse key error message
=> add support email to license key error message

.changeset/tough-guests-tease.md, packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx, packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/OptionsModal.tsx, packages/tokens-studio-for-figma/src/app/store/useTokens.test.tsx, packages/tokens-studio-for-figma/src/app/store/useTokens.tsx, packages/tokens-studio-for-figma/src/constants/TokenTypes.ts, packages/tokens-studio-for-figma/src/plugin/createLocalVariablesInPlugin.ts, packages/tokens-studio-for-figma/src/plugin/createLocalVariablesWithoutModesInPlugin.ts, packages/tokens-studio-for-figma/src/plugin/updateStyles.test.ts, packages/tokens-studio-for-figma/src/plugin/updateStyles.ts, packages/tokens-studio-for-figma/src/plugin/updateVariables.ts
The current implementation only create styles based on selected sets.
Closes #2411 
Provide a new feature that allow users to create styles based on selected themes.
=> 2411 allow users to select whether to create styles or variables or both while exporting to figma

packages/tokens-studio-for-figma/src/app/components/StylesDropdown.tsx, packages/tokens-studio-for-figma/src/app/components/ToolsDropdown.tsx
The current plugin has css issue which the portal modals (`Load examples` and `Export Styles & Variables modals`) is behind the token sets entries.
Closes #2585 
Wrapped `DropdownMenu,Content` with `DropdownMenu,Portal`.
https://github.com/tokens-studio/figma-plugin/assets/103296157/8dea4743-5b58-408f-a659-c84776058e95
=> 2585 20 tools and styles and variables menu zindex clashes with token sets

packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx
The current plugin does not have spacing between buttons in new theme modal.
Closes #2578 
Added spacing between buttons in new theme modal.
=> 2578 20 spacing missing on manage themes modal buttons

packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx, packages/tokens-studio-for-figma/src/app/components/Modal/Modal.tsx, packages/tokens-studio-for-figma/src/i18n/lang/en/manageStylesAndVariables.json
Closes https://github.com/tokens-studio/figma-plugin/issues/2579
Closes https://github.com/tokens-studio/figma-plugin/issues/2583
This pull request primarily updates the `ManageStylesAndVariables` component and the `Modal` component in the `tokens-studio-for-figma` package, and modifies the internationalization settings for the modal title. The most significant changes include setting the initial state of `showOptions` to `true`, adjusting the conditions for showing the `OptionsModal`, altering the `marginBottom` style in the `Modal` component, and updating the modal title in the internationalization settings.
use the export to figma modal
=> 2.0: Fix modal issues

packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx, packages/tokens-studio-for-figma/src/utils/alias/getAliasValue.ts, packages/tokens-studio-for-figma/src/utils/is/isSingleInternalTokenValueObject.ts, packages/tokens-studio-for-figma/src/utils/is/isSingleTokenValueObject.ts
Closes https://github.com/tokens-studio/figma-plugin/issues/2574
Closes https://github.com/tokens-studio/figma-plugin/issues/2573
The edit token form uses `internalToken` which is our internal token object. When resolving, we were relying on the `isSingleTokenValueObject` to give us the proper resolution based on $value or value. However, internally we always store `value`. Changed this so that internally we have the proper results.
Before:
After:
=> 2.0: fix alias in edit token form

packages/tokens-studio-for-figma/package.json, packages/tokens-studio-for-figma/src/app/components/LoadingBar.tsx, packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx, packages/tokens-studio-for-figma/src/app/store/useTokens.tsx, packages/tokens-studio-for-figma/src/constants/BackgroundJobs.ts, packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts, packages/tokens-studio-for-figma/src/plugin/setEffectValuesOnTarget.ts, packages/tokens-studio-for-figma/src/plugin/updatePluginDataAndNodes.ts, yarn.lock
Fixes https://github.com/tokens-studio/figma-plugin/issues/2614
Also changes behavior of styles and variables menu to close on export
Adds a check to only create variables or styles if either there's some selected sets/themes, as well as the various settings were checked
Changes the logic to await creation of variables before we're creating styles to make sure users just need to run it once. Also added checks to make sure we're only creating when needed.
Create variables using either modes as well as a combination of styles and variables
https://github.com/tokens-studio/figma-plugin/assets/4548309/ef5d92fd-7e50-408c-bba4-818183a74828
=> 2.0: Variable and style creation improvements

packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ExportSetsTab.tsx, packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ExportThemesTab.tsx, packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx, packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/OptionsModal.tsx, packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/useExportSetsTab.tsx, packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/useExportThemesTab.tsx, packages/tokens-studio-for-figma/src/i18n/lang/en/manageStylesAndVariables.json
The export tab for variables / styles had a re-render that was caused by the dialog coming from a hook. this fixes this.
In addition to the re-render, optimizes styling of the `Options` dialog to not use as much vertical space.
The changes in this PR seem large, but it's really just moving the render part of the hook out to its own files, and then add some styling.
The other change this introduces is to treat "color" as a toggle. We dont want users to create both styles and variables for colors at the same time, this is always unintended. I now changed it so it is a toggle, if color is set true, the other will be set to false.
Interact with the manage styles and variables modal
Before:
https://github.com/tokens-studio/figma-plugin/assets/4548309/bbc48686-9677-45ab-9a76-aa630b3c2691
After: …
=> fix re-render of manage styles modal (sets) + polish

packages/tokens-studio-for-figma/src/app/components/JSONEditor.tsx, packages/tokens-studio-for-figma/src/app/components/TokenGroup/TokenGroupHeading.tsx, packages/tokens-studio-for-figma/src/app/components/TokenSetTreeItemContent.tsx, packages/tokens-studio-for-figma/src/selectors/activeApiProviderSelector.ts, packages/tokens-studio-for-figma/src/selectors/index.ts, packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio/deleteTheme.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio/saveTheme.ts
Closes https://github.com/tokens-studio/studio-app/issues/872
Closes https://github.com/tokens-studio/studio-app/issues/875
- fixes complex tokens: composition, typography, border and boxShadow
- disabled features for users using Tokens Studio sync (features not available in the platform): operations on token groups, duplicate token set, JSON edit
=> 872 disable features for studio sync

packages/tokens-studio-for-figma/src/app/components/PushDialog.tsx, packages/tokens-studio-for-figma/src/app/components/StorageItemForm/BitbucketForm.tsx, packages/tokens-studio-for-figma/src/app/store/providers/bitbucket/bitbucket.tsx, packages/tokens-studio-for-figma/src/i18n/lang/en/settings.json, packages/tokens-studio-for-figma/src/i18n/lang/en/storage.json, packages/tokens-studio-for-figma/src/storage/BitbucketTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/GitTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/__tests__/BitbucketTokenStorage.test.ts, packages/tokens-studio-for-figma/src/types/StorageType.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2672
- Adds a new `username` field to bitbucket storage provider which is required for App passwords
- Authenticates using that username
=> 2.0: fix bitbucket sync basic auth

packages/tokens-studio-for-figma/jest.config.ts, packages/tokens-studio-for-figma/package.json, packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/dynamicSets/externalLoader.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/dynamicSets/fetchDynamicTokenSetData.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/dynamicSets/index.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/createTokenMutation.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/deleteTokenMutation.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/getGeneratorQuery.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/getProjectDataQuery.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/getTokenSetQuery.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/index.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/tokenFragment.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/updateTokenMutation.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/utils/index.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/utils/tokensStudioToToken.ts
Add support for dynamic sets.
When querying the tokens from TS we take all dynamic sets and execute the graphs so we can show tokens in the plugin.
+ fix for non color tokens that were not parsed correctly
Closes https://github.com/tokens-studio/studio-app/issues/885
Closes https://github.com/tokens-studio/studio-app/issues/884
https://github.com/tokens-studio/figma-plugin/assets/19837930/df7cd525-5836-4963-a340-26f40cfbedd0
=> [885] Add support for TS dynamic sets

packages/tokens-studio-for-figma/src/plugin/tryApplyTypographyCompositeVariable.test.ts, packages/tokens-studio-for-figma/src/plugin/tryApplyTypographyCompositeVariable.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2713
Typography styles werent created with the proper variables
Makes sure we load font async before we try to apply the variable as that's required.
Test the file in the issue and try to follow reproduction steps
=> fix typography vars

packages/tokens-studio-for-figma/src/app/components/AddLicenseKey/AddLicenseKey.test.tsx, packages/tokens-studio-for-figma/src/app/components/AddLicenseKey/AddLicenseKey.tsx, packages/tokens-studio-for-figma/src/app/components/AppContainer/startupProcessSteps/__tests__/addLicenseFactory.test.ts, packages/tokens-studio-for-figma/src/app/components/AppContainer/startupProcessSteps/addLicenseFactory.ts, packages/tokens-studio-for-figma/src/app/store/models/userState.ts, packages/tokens-studio-for-figma/src/utils/addLicenseKey.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2719
Previously `addLicenseKey` was a side-effect in state. This caused us to not await the response of this, something in the upgrade to 2.0 must've caused this to become apparent.
I now changed it so that addLicenseKey is a dedicated function that we properly await. Doing so the plugin now awaits license key response before we move on to other parts of the startup, also fixing our launch darkly issues.
https://github.com/tokens-studio/figma-plugin/assets/4548309/b7722b8a-2e2b-47ba-9b6f-b5b6c955eadd
https://github.com/tokens-studio/figma-plugin/assets/4548309/cec4d03f-051e-40f4-a149-ea26b731bbc6
=> 2.0: fix startup

packages/tokens-studio-for-figma/src/app/components/MoreButton/MoreButton.tsx, packages/tokens-studio-for-figma/src/app/components/StyledDragger/DragGrabber.tsx, packages/tokens-studio-for-figma/src/app/components/StyledDragger/StyledDragButton.tsx, packages/tokens-studio-for-figma/src/app/components/StyledDragger/StyledGrabber.tsx
Closes [#2720](https://github.com/tokens-studio/figma-plugin/issues/2720)
Draggable items become undraggable when in read-only mode (i.e. user does not have full permissions to edit, reorder, etc), making multiple screens in the plugin look strange due to the missing space on the left hand side. This PR ensures the space for the grabber remains.
* Adds a `canReorder` variant to `StyledDragger` that shows / hides the grabber icon based on its boolean value
* Cleans up redundant styling in `StyledDragButton`, which was overriding the visibility behaviour of the grabber
* Unrelated: fixes a missing key in children warning coming from `MoreButton`
👀 Note the yellow squares highlighting the difference when user is free (i.e. `editProhibited`):
* Grabber icon (three horizontal lines) not …
=> #2720: fix left missing padding in draggable items

packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ThemeStyleManagementCategoryStyleEntry.tsx, packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ThemeVariableManagementEntry.tsx
Closes [#2153](https://github.com/tokens-studio/figma-plugin/issues/2153#issue-1844490330)
Managing "Styles & Variables" within the theme editing modal would not display the full necessary info to attach or detach these. We now ensure the items don't overflow its parent container and add a tooltip on hover to provide all the details
* Create a style or variables with long names and / or value
* Click on the 'Theme' dropdown ---> 'Manage Themes'
* Edit any theme ---> 'Styles & Variables' tab
* Note how the name, value and detach | attach option are well contained + tooltip appears on hover
=> fix: display full styling / variable info on theme management

packages/tokens-studio-for-figma/src/app/components/DownshiftInput/DownshiftInput.tsx, packages/tokens-studio-for-figma/src/app/components/DownshiftInput/MentionInput.tsx, packages/tokens-studio-for-figma/src/app/components/DownshiftInput/StyledDownshiftInput.tsx, packages/tokens-studio-for-figma/src/app/components/DownshiftInput/mentions.css, packages/tokens-studio-for-figma/src/app/components/TokenListing.tsx
Closes [#2147](https://github.com/tokens-studio/figma-plugin/issues/2147#issue-1839939066) (+ reopens old PR https://github.com/tokens-studio/figma-plugin/pull/2753)
Fixes UI issues around the search functionality when editing tokens, from an overflowing dropdown portal component to hidden names and values due to ellipsis when long.
- Needs design review before merging
- Several less-than-ideal styling overrides to be addressed in following improvement sprints
For very complex token naming hierarchies, the UI breaks at various places. To set up, ensure you have a variety of tokens with long names (i.e. `very-long-square.wrapping-text-behaviour-token-name.white-background-label-action.ghost-variant.large-cta-just-for-testing-purposes.try-and-break-this-search-box`) or values.
<video …
=> fix: improves dropdown search experience

packages/tokens-studio-for-figma/src/app/components/DownshiftInput/DownshiftInput.tsx, packages/tokens-studio-for-figma/src/app/components/DownshiftInput/mentions.css
Fixes #2721 
> If users try to enter something like a long linear-gradient value and the value goes quite wide, the text input currently is not big enough to make sense of anything. Let's find a way where the input grows in height when users enter more.
MentionsInput height CSS is changed to auto; `MentionsInput` already has the `autosize` prop passed to it.
> We need to watch out for the prepending and appending button to the left so that those are still displayed correctly (likely vertical alignment top)
Handled by adding `height: auto` CSS to `<StyledPrefix ... />`. The prefix is automatically vertically aligned to the center.
1. Open `Tokens` Tab
2. Scroll down to `Typography`
3. Create a Token with a very long name
4. Click `+` (Add New Token)
5. Under the Typography fields, try …
=> Fix token value autosize

packages/tokens-studio-for-figma/src/app/components/DownshiftInput/StyledDownshiftInput.tsx, packages/tokens-studio-for-figma/src/app/components/TokenListing.tsx
Fixes some polish issues on the dropdowns / mentions that we introduced. Basically we were using too much space + the suggestions were centered
| Before | After |
|--------|-------|
| ![CleanShot 2024-05-17 at 08 48 47@2x](https://github.com/tokens-studio/figma-plugin/assets/4548309/1372d599-c0d5-480d-bfda-ed05ca17ef72) | ![CleanShot 2024-05-17 at 08 48 11@2x](https://github.com/tokens-studio/figma-plugin/assets/4548309/911a1350-ff9a-4555-93ed-edbd6ae211fa) |
| ![CleanShot 2024-05-17 at 08 48 52@2x](https://github.com/tokens-studio/figma-plugin/assets/4548309/fb1038b9-3543-44b5-a302-d27050b83dea) | ![CleanShot 2024-05-17 at 08 48 18@2x](https://github.com/tokens-studio/figma-plugin/assets/4548309/6898cbf2-88d9-41f1-97ca-0c73b3090105) |
=> 2.0: style polish on dropdowns

.github/workflows/merge.yml, sonar-project.properties
Integrates Sonarqube scanning for advanced vulnerability and static code analysis
Adds a job after merging into main to perform and update analysis in sonarqube
Test integration post merge to verify working as expected
=> Add sonarqube integration

packages/tokens-studio-for-figma/src/app/components/SingleCompositionTokenForm.tsx
Cleans up the composition form UI for long token names #2721 
Follow up PR to clean up the choose a property button having bad alignment/spacing with long token names.
Create a composition token with some long token names, e.g.
```json
{
/* ... */
"test1": {
"$type": "composition",
"$value": {
"sizing": "12",
"borderColor": "{hello-world-theme.a-very-long-color-name.try-to-break.square-cta}",
"horizontalPadding": "8",
"maxWidth": "4"
}
}
/* .... */
}
```
| Before   | After |
|----------|------:|
| ![before](https://github.com/tokens-studio/figma-plugin/assets/6757532/a6f99d7d-df15-426c-83ea-37d187021f59) | ![after](https://github.com/tokens-studio/figma-plugin/assets/6757532/81bf4ba8-735a-4bcd-9b67-9a6fbe8aed2b) |
=> Composition UI cleanup for long token names (choose property button)

packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ThemeListGroupHeader.tsx, packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ThemeListItemContent.tsx, packages/tokens-studio-for-figma/src/app/components/StyledDragger/StyledDragButton.tsx, packages/tokens-studio-for-figma/src/app/components/TokenSetItem/TokenSetItem.tsx
Closes [#2783](https://github.com/tokens-studio/figma-plugin/issues/2783) 
Draggable items only showed the dragger when the _icon_ was hovered on, instead of hovering **anywhere** on the item. This adds a styling variant to force the dragger to show when contained within a reorderable item.
* Adds a `canReorder` variant to `StyledDragButton` which shows the any grabber contained, on hover
* Passes the `canReorder` prop to all draggable items that need it
* Open the plugin
* To see draggable items:
* Have multiple layered sets in the **Tokens** tab
* Have multiple **Themes** in the themes management modal
https://github.com/tokens-studio/figma-plugin/assets/114073780/6af2b79f-ddbf-4b24-8022-21bbc653f40d
https://github.com/tokens-studio/figma-plugin/assets/114073780/fdbfc8ed-a4e9-4187-acd4-1 …
=> fix: show grabber on item hover

packages/tokens-studio-for-figma/src/utils/__tests__/trySetStyleId.test.ts, packages/tokens-studio-for-figma/src/utils/trySetStyleId.ts
Closes #2776
Previously when a user had deleted styles that were still attached to tokens, we'd try to apply the style, even though it no longer existed.
Changed the logic to *not* resolve to the stored style id if it's a 404. Instead, return early.
Create a theme and connect tokens to created styles. On prod, you'd see a bunch of 404s in addition to errors trying to apply the style. With this build, the 404s still exist, but the apply errors are no longer there.
Before (here we're attempting to apply a style resulting in the error)
https://github.com/tokens-studio/figma-plugin/assets/4548309/0982325b-5e99-4148-8f55-73513701c9c9
After (here we're exiting early and wont even try to apply the missing style)
https://github.com/tokens-studio/figma-plugin/assets/4548309/20f2cde5-8498-4914-8653- …
=> fix: 2776 404 style dont apply

.changeset/lemon-drinks-sort.md, packages/tokens-studio-for-figma/src/plugin/TokenValueRetriever.ts
Closes #2794
When a token is not connected to a variable, but the value of the token is a pure reference to a token that is connected to a variable, apply that variable, instead of what we do today, which is apply the raw hex value.
This enables users to have their semantic variables applied when their component tokens are applied - as long as they dont create component token variables.
Adds a check to where we fetch the variableReference if there's a fallback variable we could use
- Create a token called `red` in a set called `Core`, create a theme group for it and enable just that set here
- Create another token called `danger` and use `{red}` as the value, in another set called `Semantic` (no theme group required)
- Create variables
- Apply the token for `danger` and see that `red` …
=> apply fallback variable if no connected variable

packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ExportSetsTab.tsx
Previously, selecting sets to export would always persist the changes. This gives the user to option to save or cancel.
Closes [#2575](https://github.com/tokens-studio/figma-plugin/issues/2575#issue-2230356010) (N.B. screen doesn't contain a search any more)
* Renders a footer on set selection with **cancel** (destroys the set selection) or **confirm** (persists the set selection)
* Adds a `previousSelectedSets` state to remember the T-1 state and use when the user presses **cancel** (in the footer) or the **back arrow** (in the header)
* Click on 'Styles & Variables' ---> 'Export styles & variables'
* On the modal, click 'Confirm'
* Click on the 'Token Sets' tab
* Click on 'Change Sets' CTA
* Change set selections as you wish:
* Clicking on **confirm** will save the changes
* Clicking on …
=> fix: add save button to export sets modal

packages/tokens-studio-for-figma/src/app/components/Tokens.tsx, packages/tokens-studio-for-figma/src/app/components/TokensBottomBar.tsx
Closes [#2777](https://github.com/tokens-studio/figma-plugin/issues/2777#issue-2305858396) 
Removes the constant error appearing when editing JSON.
* Simply sets the JSON editor's value when it changes, without validation (`Tokens.tsx`)
* Moves the validation into `TokensBottomBar.tsx`, which is triggered when user clicks the **Save JSON** CTA
* Open the plugin
* Go into the JSON tab
* Type in a new token, manually and click on **Save JSON**
* If valid: it will persist
* If not valid: it will show an error toast 
| Before | After |
|-----|-----|
| <video height="300" src="https://github.com/tokens-studio/figma-plugin/assets/114073780/b4d31946-eaa3-4d7e-bf33-3b49641eeefc"></video> | <video height="300" src="https://github.com/tokens-studio/figma-plugin/assets/114073780/cf766e4f-e47c-43de-b5 …
=> fix: prevent errors from appearing while editing JSON

packages/tokens-studio-for-figma/src/app/components/BorderTokenDownShiftInput.tsx, packages/tokens-studio-for-figma/src/app/components/SingleBoxShadowDownShiftInput.tsx
Addresses #1928 
- when a user selects a color(via a reference token) in the border token form, the swatch shall now update dynamically.
- fixes #1928
=> fix: border token and box shadow input form color swatch to update on references

packages/tokens-studio-for-figma/src/app/components/StorageItemForm/ADOForm.tsx, packages/tokens-studio-for-figma/src/app/components/StorageItemForm/GenericVersioned.tsx, packages/tokens-studio-for-figma/src/app/components/StorageItemForm/GitForm.tsx, packages/tokens-studio-for-figma/src/app/components/StorageItemForm/JSONBinForm.tsx, packages/tokens-studio-for-figma/src/app/components/StorageItemForm/SupernovaForm.tsx, packages/tokens-studio-for-figma/src/app/components/StorageItemForm/URLForm.tsx
Closes [#2847](https://github.com/tokens-studio/figma-plugin/issues/2847#issue-2349030882)
"Read more" links to explain more about sync providers were opening in the plugin. They now open in a browser window.
* Adds `target="_blank" rel="noreferrer"` (extra safe) to all links on all applicable sync provider forms
* Go to settings
* Click on any new sync provider to add
* Click on "Read more"
https://github.com/tokens-studio/figma-plugin/assets/114073780/500de519-6ab9-40bc-9de7-57006298418d
=> fix: sync provider "Read more" links now open in browser

packages/tokens-studio-for-figma/src/plugin/applySizingValuesOnNode.ts
Closes #2426 
Changes the logic to apply min and max-width on instances
Create a component with autolayout
Create an instance of the component
Apply min/max width/height sizing through the plugin
=> Fix/ min&max width&height on instances

packages/tokens-studio-for-figma/package.json, packages/tokens-studio-for-figma/src/app/components/BranchSwitchMenuRadioElement.tsx, packages/tokens-studio-for-figma/src/app/components/InspectSearchOptionDropdown.tsx, packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ThemeGroupDropDownMenu.tsx, packages/tokens-studio-for-figma/src/app/components/MultiSelectCheckboxItem.tsx, packages/tokens-studio-for-figma/src/app/components/ThemeSelector/ThemeSelector.tsx, yarn.lock
Closes [#2851](https://github.com/tokens-studio/figma-plugin/issues/2851)
* Bumps the DS UI package version to 0.6.7 - following up from [this release](https://github.com/orgs/tokens-studio/projects/34/views/3)
* Updates all items using the radix `CheckIcon` component to instead make use of the `Check` component from **iconoir**
Run the plugin, and observe any dropdowns with ✔️ markers look the same.
=> chore: dropdown menu item indicator updates

packages/tokens-studio-for-figma/src/app/components/RemConfiguration.tsx, packages/tokens-studio-for-figma/src/i18n/lang/en/settings.json
- When a user changes the base font size from settings, either directly or via a font size token, the rem value will now be displayed in the settings with the current base font size(Default being 1 rem)
Closes #2845
=> Fix base font size display in settings

packages/tokens-studio-for-figma/src/app/components/Settings/Settings.tsx, packages/tokens-studio-for-figma/src/app/components/SyncSettings.tsx
Closes [#2772](https://github.com/tokens-studio/figma-plugin/issues/2772)
At the bottom of the plugin **Settings**, a user can toggle the permission to record the session for debugging purposes. This was not showing the `sessionId` when turned ON!
* Shows a console warning when the user toggles ON session recording won't work (i.e. in the `development` environment) - will work on `production`, `alpha` & `beta`.
* Polishes the UI when the session recording is ON
* 🤔 📈 Not sure if the Session Replay(s) take time to process - as I [could not find them on the dashboard](https://figma-tokens.sentry.io/replays/?project=5220409&statsPeriod=14d)
* Upgrading our `@sentry/react` package. Although for replay to work we are [covering the minimum requirements of the SDK to be …
=> fix: debug mode now shows `sessionId`

packages/tokens-studio-for-figma/src/app/components/DownshiftInput/MentionInput.tsx, packages/tokens-studio-for-figma/src/app/components/DownshiftInput/StyledDownshiftInput.tsx, packages/tokens-studio-for-figma/src/app/components/DownshiftInput/mentions.css
Closes [#2878](https://github.com/tokens-studio/figma-plugin/issues/2878#issue-2361535058) 
The ability to view full token data (specifically names) was a pain point for users, which was solved by stacking these ([PR](https://github.com/tokens-studio/figma-plugin/pull/2759)). Negative feedback means we are reverting this, and aligning both views to horizontally display the data.
* Adapts `mentions.css` & `Mentions` to have the same look & feel as `DownshiftInput` when displaying an item on the list
* Allows name & resolved value to grow equally, while displaying a tooltip with these full values
* Run the plugin
* Create a new token with a loooooong name
* Go and create a composition token (for example)
* Search for the loooooong name = DownshiftInput
* Start typing `{...` = Mentions
| …
=> fix: horizontal token display for all dropdown lists (search input & mentions)

packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx, packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ThemeGroupDropDownMenu.tsx, packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ThemeListGroupHeader.tsx
Fixes #2880  
1. Go to the Manage Themes modal by clicking `Theme: None` or `Theme: {theme_name_here}`
2. Click `Manage Themes`
3. Click the `+ New Theme` button
4. Check visually that the new UI is being used
5. Try entering a group name and theme name
- Also fixes a bug around empty group name populating the input when renaming the group name
- Added text input placeholders for `Add group` and `Theme name`
| **Before** | **After** |
|--------|--------|
| <img width="477" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/6757532/3d820ec3-cae1-4985-910a-c2a21fc9c06d"> | <img width="491" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/6757532/1a2ff199-3c6f-47c7-8967-3a51ceb8a695"> |
| <img width="481" alt="image" …
=> Revert Manage Themes dialog group/theme name input change

packages/tokens-studio-for-figma/src/app/store/models/settings.tsx, packages/tokens-studio-for-figma/src/utils/__tests__/uiSettings.test.ts, packages/tokens-studio-for-figma/src/utils/uiSettings.ts
Fixes: https://github.com/tokens-studio/figma-plugin/issues/2876
This sets the default for those options when no value is provided correctly, as in if nothing is stored locally, we just set variablesColor to true, not both.
=> fix: variables styles color remember

packages/tokens-studio-for-figma/src/app/components/RemConfiguration.tsx
- Now base font size's reference will be displayed directly outside in the settings tab
- when the referenced token is deleted or invalid, it shall display the broken link in red
- Resolves #2875 
In dark mode:
=> feat: Enhance base font size display in settings tab

packages/tokens-studio-for-figma/src/app/components/Modal/Modal.tsx, packages/tokens-studio-for-figma/src/app/components/PullDialog.tsx, packages/tokens-studio-for-figma/src/app/components/PushDialog.tsx, packages/tokens-studio-for-figma/src/app/store/useTokens.tsx
Closes #2909
Modals in 2.0 are overall too big - they span the full window size.
Introduce a max width for our modals so that they don't go as wide.
=> 2.0 Polish modal size

packages/tokens-studio-for-figma/src/plugin/createLocalVariablesInPlugin.ts, packages/tokens-studio-for-figma/src/plugin/createLocalVariablesWithoutModesInPlugin.ts, packages/tokens-studio-for-figma/src/plugin/mergeVariableReferences.ts
Closes https://github.com/tokens-studio/figma-plugin/issues/2906
When we're creating variables, we currently use themes that are active to inform what variables should be used as references. However, if those theme groups aren't active, we won't know what variable references to use for tokens and will fall back to raw hex values inside variables. Especially in multi-file setup users sometimes only enable one theme group, meaning they won't have the necessary references available.
Changes the logic to add another set of themes to the merge function, so that the references from the current theme group have preference, but after that we'll take into account other themes. 
Note that this is kind of flawed as we will pick the first available variable reference that we find. However, I'd say …
=> 2.0: Fix variable references when references aren't coming from any active themes

packages/tokens-studio-for-figma/src/utils/convertTokensToObject.ts
Closes #2907
With 2.0 we seem to have introduced a regression when it comes to the order of token keys. We made it so that `type` always comes first, then `value`, and so on. This is bad because we need to respect users key ordering.
With this PR we're now respecting the order and keeping it the same by not destructuring the object.
As you can see in this screenshot we reordered keys, even though the user didnt specify that.
Here's me after the change just adding a modifier - note how it preserves the order of `value` first.
=> 2.0: Fix order of keys when pushed to remote

packages/tokens-studio-for-figma/src/storage/BitbucketTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/__tests__/BitbucketTokenStorage.test.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2905
Users reported bitbucket sync behaves weirdly when creating a new branch. It takes a different source branch than specified.
Looked into the code and we naively took the first branch that came back from the list of branches. Changed it so that we use the specified branch name.
=> fix bitbucket create branch from having wrong origin

packages/tokens-studio-for-figma/src/app/components/DownshiftInput/DownshiftInput.tsx, packages/tokens-studio-for-figma/src/app/components/DownshiftInput/MentionInput.tsx, packages/tokens-studio-for-figma/src/utils/color/getColorSwatchStyle.ts, packages/tokens-studio-for-figma/src/utils/color/index.ts
Closes [#2951](https://github.com/tokens-studio/figma-plugin/issues/2951#issue-2385828332)
Colors with semicolons were not applying to the color swatches due to an error when the DOM CSS styling was attempting to be applied
* Adds a small utility that strips a semicolon from a string
* Uses the utility for correct styling in search and mentions
1. Create a color token as a gradient (i.e. `linear-gradient(to right,#dc573c,#247efc);`)
2. Create or edit another color token - search by name or alias
3. See the gradient showing on the swatch
| Before | After |
| ----- | ----- |
| <img width="200" alt="Screenshot 2024-07-02 at 12 04 03" src="https://github.com/tokens-studio/figma-plugin/assets/114073780/204889ed-733b-4b75-a20f-98c2f1f60c51"> | <img width="200" alt="Screenshot 2024-07-02 at 12 …
=> fix: color swatches to show colors with gradients

.github/workflows/node.js.yml, packages/tokens-studio-for-figma/cypress/e2e/tokens.cy.js, packages/tokens-studio-for-figma/src/app/components/ColorTokenForm.tsx, packages/tokens-studio-for-figma/src/app/components/ConfirmDialog.tsx, packages/tokens-studio-for-figma/src/app/components/Footer.tsx, packages/tokens-studio-for-figma/src/app/hooks/useConfirm.tsx, packages/tokens-studio-for-figma/src/app/store/models/uiState.tsx, packages/tokens-studio-for-figma/src/app/store/useManageTokens.tsx
Test for #2885  
Test for #2779 
- Adds Cypress test for clicking outside Select (to verify this bug isn't reintroduced)
- Cypress test for resolving duplicate modal
- Fixes GitHub CI workflow action for test coverage
```sh
cd packages/tokens-studio-for-figma
yarn build:cy
yarn serve
yarn cy:run
```
=> Cypress tests for select in modal and duplicate resolving

packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/__tests__/getThemeReferences.test.ts, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/getThemeReferences.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2987
Fixes the name normalization as it was performed too late and not before we actually made the comparison.
Also added a test to ensure this doesnt happen
Create a setup as described or take this .fig and try to theme switch before and after
[theme-switch-bug.fig.zip](https://github.com/user-attachments/files/16168421/theme-switch-bug.fig.zip)
https://github.com/user-attachments/assets/49d6650e-d6e1-4863-b405-a115719784df
https://github.com/user-attachments/assets/6efe54e6-ba64-4b01-92c0-7fda87b5db4f
=> fix local variable references normalization

packages/tokens-studio-for-figma/src/app/components/ImportedTokensDialog.test.tsx, packages/tokens-studio-for-figma/src/app/components/ImportedTokensDialog.tsx, packages/tokens-studio-for-figma/src/app/store/models/tokenState.tsx, packages/tokens-studio-for-figma/src/app/store/useManageTokens.tsx
Closes [#2529](https://github.com/tokens-studio/figma-plugin/issues/2529)
Updating a variable value in Figma was not reflected in the plugin until views were changed. This ensures tokens updated are immediatly reflected when importing variables.
* The method `importMultipleTokens` within the `useManageTokens` hook, now uses the sibling methods of `editSingleToken` & `createSingleToken` to dispatch update actions
* `ImportedTokensDialog` updates the payload sent to `importMultipleTokens` in order to update tokens correctly
* Cleans up unused assets in relevant files
🎨 [Simple Figma file](https://www.figma.com/design/J6EJHGZ8UxlQhTbhaPOJbX/Import-variables-update?node-id=0-1&t=T9WFrm7lYgUk5XSI-1)
1. Create a local variable in Figma. In this example: `test-color: #F0B0B0`
2. Open the plugin. …
=> fix: update token changes on variable import

packages/tokens-studio-for-figma/src/app/components/ChangedStateList.tsx, packages/tokens-studio-for-figma/src/app/components/ChangedTokenItem.tsx, packages/tokens-studio-for-figma/src/app/components/PullDialog.tsx
Fixes #2980 
- Reverts GitHub pull modal to `large` instead of `fullscreen`
- Fixes some CSS issues (width overflow and word break), related to less available screen real estate
- Setup a GitHub repo
- Sync tokens to the GitHub repo
- Make changes (i.e. rename the set names)
- Click the `Pull From GitHub` button in the bottom footer bar
=> Revert github pull to large modal with css fixes

packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/SingleThemeEntry.tsx, packages/tokens-studio-for-figma/src/app/components/StyledDragger/DragItem.tsx
Cloes #2981  
- In `src/selectors/editProhibitedSelector.ts`, replace `(state) => state.editProhibited` with `() => true`
- Open the `Manage Themes` modal
- Verify that there is padding
**Before**
**After**
=> Fix manage themes padding

packages/tokens-studio-for-figma/src/utils/tryApplyVariableId.test.ts, packages/tokens-studio-for-figma/src/utils/tryApplyVariableId.ts
N/A - discovered while testing [#2991](https://github.com/tokens-studio/figma-plugin/issues/2991)
Removes warning messages when applying styling to nodes:
> Calling setBoundVariable with a variable id is deprecated. Please pass the variable node instead.
Passes an instance of the **variable** instead of a variable **id** to the `setBoundVariable()` method.
See Figma Plugin API update docs: https://www.figma.com/plugin-docs/updates/page/2/#methodproperty-usage-changes
* Open the plugin 
* Apply any styling to nodes
* See there are no warnings on the console!
=> chore: remove style setting on node warning

packages/tokens-studio-for-figma/src/utils/tokenset/__tests__/findParentIndexToInsertSet.test.ts, packages/tokens-studio-for-figma/src/utils/tokenset/__tests__/updateTokenSetsInState.test.ts, packages/tokens-studio-for-figma/src/utils/tokenset/findParentIndexToInsertSet.ts, packages/tokens-studio-for-figma/src/utils/tokenset/updateTokenSetsInState.ts
Closes [#3007](https://github.com/tokens-studio/figma-plugin/issues/3007#issue-2413515391) 
When creating a new set, even if nested, it was always placed at the end of list.
* Creates a `findParentIndexToInsertSet` helper, which takes in a list of sets and a set name, and returns the index where to insert the new set!
* Uses the helper in the `updateTokenSetsInState` method
* Create and update tests
* Open the plugin and ensure you have some sets created, [set-ordering.zip](https://github.com/user-attachments/files/16286192/set-ordering.zip), for example:
```
- base
- yellow-brand
- red-brand
```
* Create a new nested set (1 layer) like `base/light` ---> Note how the set is **next** to `base`
* Create a new nested set (2 layers) like `yellow-brand/light/mobile`  ---> Note how the set is …
=> fix: maintain set ordering on creation

packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx, packages/tokens-studio-for-figma/src/app/components/SingleCompositionTokenForm.tsx
Fixes https://github.com/tokens-studio/figma-plugin/issues/3020
Fixes https://github.com/tokens-studio/figma-plugin/issues/3016
Includes formatting changes as well (automatically on save)
also includes a fix for composition token forms (by making sure the longest string is readable)
=> fix variable rename pos and composition form

.github/workflows/node.js.yml, .github/workflows/release.yml
Make it easier to share individual builds to test.
* Adds an action [after the artifact is stored](https://github.com/tokens-studio/figma-plugin/blob/release-139/.github/workflows/node.js.yml#L32) that posts a link to download it. Runs on every CI once a PR is created.
* Uses `actions/upload-artifact@v4` to have access to the `artifact-url` it outputs. Older versions will also be deprecated soon 👉 [read more here](https://github.com/actions/upload-artifact?tab=readme-ov-file#actionsupload-artifact)
[See automated comment below](https://github.com/tokens-studio/figma-plugin/pull/3029#issuecomment-2250833012) 😄
=> chore: add action to post link to built artifact

packages/tokens-studio-for-figma/src/app/components/createTokenObj.test.tsx, packages/tokens-studio-for-figma/src/utils/convertTokensToObject.test.ts, packages/tokens-studio-for-figma/src/utils/convertTokensToObject.ts, packages/tokens-studio-for-figma/src/utils/setTokenKey.test.ts, packages/tokens-studio-for-figma/src/utils/setTokenKey.ts
Closes [#3017](https://github.com/tokens-studio/figma-plugin/issues/3017#issue-2424807255)
Switching between legacy and W3C DTCG format would wrongly push duplicated keys on the remotes 
(i.e. `type: 'color'` and `$type: 'color'`) causing issues on tokens when using them.
* Creates a helper called `setTokenKey` which checks the format being used before adding | removing keys and values on the token
* Uses this helper in `convertTokensToObject`, which is the core method used in **RemoteTokenStorage** before pushing to remotes!
* Adapts and adds test coverage to these methods
📖 🔨 Test file: [colors.json](https://github.com/user-attachments/files/16374078/colors.json)
☝️ Set up alongside a remote providers (this was tested with Github)
1. Note how these are in **legacy** format
2. Switch to …
=> fix: prevents duplicated format sensitive keys on tokens when pushing to remotes

packages/tokens-studio-for-figma/src/app/components/DuplicateResolver/ResolveDuplicateTokenGroup.tsx, packages/tokens-studio-for-figma/src/app/components/TokenTooltip/SingleCompositionValueDisplay.tsx, packages/tokens-studio-for-figma/src/app/components/TokenTooltip/SingleTypographyValueDisplay.tsx, packages/tokens-studio-for-figma/src/app/components/TokenTooltip/TokenTooltipContentValue.tsx, packages/tokens-studio-for-figma/src/app/components/__tests__/TokenBottomBar.test.tsx
Fixes #3025 
- Create duplicate typography, composite and box shadow token values by switching to the production version and use `Duplicate Group`
- Open the Resolve Duplicates Modal and verify that the previews show correctly and the plugin doesn't crash
=> Fix resolve duplicate modal crash with object values

packages/tokens-studio-for-figma/src/app/store/models/reducers/__tests__/assignStyleIdsToCurrentTheme.test.ts, packages/tokens-studio-for-figma/src/app/store/models/reducers/tokenState/assignStyleIdsToCurrentTheme.ts, packages/tokens-studio-for-figma/src/app/store/useTokens.tsx, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/createStyles.ts, packages/tokens-studio-for-figma/src/plugin/updateStyles.test.ts, packages/tokens-studio-for-figma/src/plugin/updateStyles.ts, packages/tokens-studio-for-figma/src/types/AsyncMessages.ts
Fixes the issue our users have been having with RC11 on https://tokens-studio.slack.com/archives/C073SSG7DC7/p1722027287469299   if they were exporting to Styles we would ignore certain token sets. This was due to the new behavior we introduced in RC11 that made it so that when you create styles we iterate over each theme and look at each own on its own.
Its obvious our users arent setup for this as they have themes that are using `disabled` token sets and not as would be correct set as source.
This PR reverts the behavior while keeping the behavior that the original issue there was trying to solve (attaching styles wasnt working anymore)
Create a few themes and then create styles.
=> fix: revert and fix attach when creating styles

packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts
Follow-up PR
Fixes #3014  
- Try applying this composition token to a node and verify that it applies and doesn't error:
```
{
"test": {
"value": {
"borderColor": "#FFF000",
"sizing": "{medium} + 40",
"fill": "#0fa",
"borderRadiusTopLeft": "16 + 8",
"backgroundBlur": "12px"
},
"type": "composition"
}
}
```
=> Fix composition tokens not applying raw values for colours

packages/tokens-studio-for-figma/src/app/components/AppContainer/startupProcessSteps/__tests__/pullTokensFactory.test.ts, packages/tokens-studio-for-figma/src/app/components/AppContainer/startupProcessSteps/pullTokensFactory.ts, packages/tokens-studio-for-figma/src/app/components/BranchSelector.tsx, packages/tokens-studio-for-figma/src/app/components/Footer.tsx, packages/tokens-studio-for-figma/src/app/components/ImportedTokensDialog.test.tsx, packages/tokens-studio-for-figma/src/app/components/modals/CreateBranchModal.tsx, packages/tokens-studio-for-figma/src/app/store/providers/ado/ado.tsx, packages/tokens-studio-for-figma/src/app/store/providers/bitbucket/bitbucket.tsx, packages/tokens-studio-for-figma/src/app/store/providers/generic/versionedStorage.ts, packages/tokens-studio-for-figma/src/app/store/providers/github/github.tsx, packages/tokens-studio-for-figma/src/app/store/providers/gitlab/gitlab.tsx, packages/tokens-studio-for-figma/src/app/store/providers/jsonbin.tsx, packages/tokens-studio-for-figma/src/app/store/providers/supernova/supernova.tsx, packages/tokens-studio-for-figma/src/app/store/providers/tokens-studio/tokensStudio.tsx, packages/tokens-studio-for-figma/src/app/store/providers/url.tsx, packages/tokens-studio-for-figma/src/app/store/remoteTokens.test.ts, packages/tokens-studio-for-figma/src/app/store/remoteTokens.tsx
Closes #3028 (_potentially_, also #3031 & #2984)
Differences between remote and local changes were inconsistently wrong.
* Instantly saves the **pushed** changes on the `remoteState` (Redux global state)
* Always pulls remote data on **plugin startup** and sets them on the `remoteState` (Redux global state) without overriding the local changes (if they exist)
> ⚠️ ⚠️ ⚠️ This was only tested using GitHub ⚠️ ⚠️ ⚠️ 
Setup a remote storage of your choice. I used these tokens: [simple-tokens.json](https://github.com/user-attachments/files/16426192/simple-tokens.json) 🎨 
* Locally change a token
* Don't push the changes
* Close & open the plugin
* See the same changes are still there!
https://github.com/user-attachments/assets/af98fba3-baf4-44aa-91ac-90a8b5a49a8d
* Locally change a token
* Push …
=> fix: ensure remote changes are correctly tracked in the plugin

packages/tokens-studio-for-figma/src/plugin/helpers.ts, packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.test.ts, packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts, packages/tokens-studio-for-figma/src/plugin/updateVariables.ts
Fixes https://github.com/tokens-studio/figma-plugin/issues/2991
Fixes an issue where number tokens that contained a unit (something we should *not* encourage, but currently a few users have this setup) were created as 0 values in variables.
Adds a step to the transformValue step and `setValuesOnVariable` step that transforms the value of number variables
Use the testing file from @SamIam4Hyma and test
=> Add support for transform numbers

packages/tokens-studio-for-figma/src/plugin/pullVariables.test.ts, packages/tokens-studio-for-figma/src/plugin/pullVariables.ts
Closes [#3045](https://github.com/tokens-studio/figma-plugin/issues/3045)
When there was an error importing Variables from Figma, the whole process stopped.
Adds a try / catch block when importing Figma Variables, therefore any errors are shown in the console, and the Plugin continues to import the rest.
* Go to this file: [DS](https://www.figma.com/design/bcF9PczrsSsorC4zWO2WNv/DS?node-id=5002-58299&t=Kk7WjM9H6ZGwzvzd-0) 
* See that the local variables are there (6 collections)
* Open the plugin -> Styles & Variables -> Import Variables (Tick "Convert numbers to dimensions")
* It will take some time ⏳ 
* See the handled error message _("Error handling variable")_ & tokens in the Plugin ✨
=> fix: handle errors when importing variables

packages/tokens-studio-for-figma/src/app/store/providers/ado/ado.tsx, packages/tokens-studio-for-figma/src/app/store/providers/bitbucket/bitbucket.tsx, packages/tokens-studio-for-figma/src/app/store/providers/generic/versionedStorage.ts, packages/tokens-studio-for-figma/src/app/store/providers/github/github.tsx, packages/tokens-studio-for-figma/src/app/store/providers/gitlab/gitlab.tsx, packages/tokens-studio-for-figma/src/app/store/providers/jsonbin.tsx, packages/tokens-studio-for-figma/src/app/store/providers/supernova/supernova.tsx, packages/tokens-studio-for-figma/src/app/store/providers/tokens-studio/tokensStudio.tsx, packages/tokens-studio-for-figma/src/app/store/providers/url.tsx, packages/tokens-studio-for-figma/src/app/store/remoteTokens.tsx
Closes #2984 
Ensures that every time remote changes are made, the provider data is saved in the local state as `lastSyncedState`. Treat this as a follow-up from the merged PR https://github.com/tokens-studio/figma-plugin/pull/3035
Dispatches data to set `setLastSyncedState` (the same as `setRemoteData`) so that `tokenState` is up to date with the freshest remote status.
* Open the plugin
* Make token changes
* Push changes
* Continue to use the plugin and see no 'notification' bubble shows to push anything!
https://github.com/user-attachments/assets/6568d740-1039-4d59-b546-842ca90f1454
=> fix: store last synced state from remote

packages/tokens-studio-for-figma/src/plugin/TokenValueRetriever.ts, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/setNodeData.ts, packages/tokens-studio-for-figma/src/plugin/updateStyles.ts
Closes #3049
When users were exporting styles that had either **"Ignore first part of token name for styles"** or **"Prefix styles with active theme name"** toggled **ON**, the styles applied to the node would reference the _resolve value_ instead of the _token name_
* Passes the correct props related to the toggle options onto the `TokenValueRetriever` 
* When "**Ignore first part...**" is toggled, the token at hand is only manipulated when its path length is over 1
🔨 Tested with [tokens.json](https://github.com/user-attachments/files/16510283/tokens.json)
⏯️ Styles & Variables -> Export Styles & Variables -> Tick everything under **Styles** -> Select Themes / Token Sets (ensure there's at least 1 active one)
https://github.com/user-attachments/assets/edea2f82-f29e-40fd-9c31-69ddf20dbeac …
=> fix: exporting and applying styles correctly references the tokens

packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ExportSetsTab.tsx, packages/tokens-studio-for-figma/src/plugin/figmaTransforms/fontWeight.ts, packages/tokens-studio-for-figma/src/plugin/helpers.ts, packages/tokens-studio-for-figma/src/plugin/setNumberValuesOnVariable.ts, packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts, packages/tokens-studio-for-figma/src/plugin/updateVariablesToReference.ts
Closes #3054
Users were facing an endless `Creating variables…` loader that didnt go away
Adds a try { } catch { } block to the `updateVariableToReferences` function that safely proceeds creating variables if we encounter an error trying to set a variable. The reason for this was that sometimes we were passing in the wrong type for a variable that expected something else.
This PR also adds checks to make sure that we do not attempt to set the value if it is `NaN` and logs a warning message if this is the case. As well as adding a check to see if the value is still a raw value.
Try to recreate with the token sets shared in https://hyma-team.slack.com/archives/C06RHB9RT2B/p1723030872522979
=> fix endless loader

packages/tokens-studio-for-figma/src/app/components/ChangedStateList.tsx, packages/tokens-studio-for-figma/src/app/components/Footer.tsx, packages/tokens-studio-for-figma/src/app/components/PullDialog.tsx, packages/tokens-studio-for-figma/src/app/components/PushDialog.tsx, packages/tokens-studio-for-figma/src/app/store/models/uiState.tsx, packages/tokens-studio-for-figma/src/app/store/remoteTokens.test.ts, packages/tokens-studio-for-figma/src/app/store/remoteTokens.tsx, packages/tokens-studio-for-figma/src/hooks/useChangedState.ts
Closes #3057
We previously showed the wrong state when pulling changes, which had the "new state" on the left side which had shown this as the "old state".
Also, the indicator didnt disappear. The reason for that was that this was a local state variable, which was not reset when pulling changes - only when 60 seconds pass.
This PR changes things so that we have a uiState for the remote change indicator, which is reset when pulling changes. Also, we show the correct state when pulling changes by having two different changedState implementations (which just reverses the order)
Have two files open that have the same remote. Change tokens in one file and push. Then wait 60 seconds for the indicator to appear and pull the changes. Also, when pushing and pulling, look at the token values in the …
=> fix remote change indicator

packages/tokens-studio-for-figma/src/app/components/StorageItemForm/BitbucketForm.tsx
simple change of position of name help text in the Bitbucket Sync Form
=> fix: position of name help text in BitBucket Form

.changeset/silly-beds-drum.md, packages/tokens-studio-for-figma/src/app/sentry.ts
Closes #3073 
We didnt await setupReplay before, which seems to have caused some issues initializing our CSS styles.
Adds a 2 second timeout to session recording.
Enable remote storage, enable session recording. Restart plugin. All should look good. With 2.0 prod it looks broken.
Before:
After:
=> Fixes broken UI issue

.changeset/mighty-cooks-punch.md, packages/tokens-studio-for-figma/src/storage/BitbucketTokenStorage.ts
Resolves #3070 
In the 2.0 version of the plugin, the users are unable to fetch sets from Bitbucket remote storage, when the sets are in a folder structure. For example if a set exists as folder1/set1, it shall be unable to fetch it and even delete the existing folder sets.
- This PR scans through the response of the Bitbucket API and filters the directories as well(which was earlier being ignored), and then fetches the sets in json format from each of those folders.
- It then scans through all the json files(which was being done previously as well, but now includes the folder structure sets as well)
- Create a set in a folder,
- Add some tokens in the set
- Push to Bitbucket
- Then pull from Bitbucket
- Expected: It should not wipe the folder sets and pull the sets in the folder
=> Fix bitbucket folder sync pull

.changeset/four-monkeys-deny.md, packages/tokens-studio-for-figma/src/app/components/PushDialog.tsx, packages/tokens-studio-for-figma/src/app/store/providers/ado/ado.tsx, packages/tokens-studio-for-figma/src/app/store/providers/bitbucket/getBitbucketCreatePullRequestUrl.ts, packages/tokens-studio-for-figma/src/app/store/remoteTokens.test.ts, packages/tokens-studio-for-figma/src/storage/ADOTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/__tests__/ADOTokenStorage.test.ts, packages/tokens-studio-for-figma/src/types/StorageType.ts
Closes #3067
Users were unable to push changes to ADO when not using their **main** branch (initial bug). Then expanded to additional bugs as outlines in the issue.
* Fetches the last commit ID based on the ADO branch selected in the plugin so that changes can be reliably pushed upsteam (✅ Fixes issue **num. 2**)
* Fixes BitBucket PR creation URL 
* Adds safety `rel` tag on create URL CTA
* Adds a `previousSourceBranch` constant on the ADO Storage Solution, which will use that branch as a source when creating new ones (✅ Fixes issue **num. 3**)
* Adds extra checks when editing the ADO settings, as well as a fallback if the user never pushes the branch / file updates to the remote (✅ Fixes issue **num. 4**)
* Set up an Azure DevOps repository
* Select another branch that's not **main**
* …
=> fix: ADO pushes to correct branch & BB create PR link update

.changeset/shaggy-sheep-know.md, packages/tokens-studio-for-figma/src/storage/__tests__/ADOTokenStorage.test.ts
Closes [#3085](https://github.com/tokens-studio/figma-plugin/issues/3085)
Changes to the way that ADO works meant that the fetch mocks had to be updated to test the functionality correctly
Run the tests (or see them in the pipeline) - see that `ADOTokenStorageTest.ts` ✅
=> fix: ADO single and multi file tests

.changeset/beige-cameras-kneel.md, packages/tokens-studio-for-figma/src/app/store/providers/__tests__/clientFactory.test.ts, packages/tokens-studio-for-figma/src/app/store/providers/gitlab/gitlab.tsx, packages/tokens-studio-for-figma/src/app/store/remoteTokens.test.ts, packages/tokens-studio-for-figma/src/storage/GitlabTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/__tests__/GitlabTokenStorage.test.ts, packages/tokens-studio-for-figma/src/types/StorageType.ts
Closes #3076
Users were experiencing errors when switching from single / multi files or referencing new branches. Similar to ADO: https://github.com/tokens-studio/figma-plugin/pull/3071
* Adds checks in the GitLab client to create the necessary branch / file / directory before pushing
* Creates the new branch based on the currently selected one in the plugin
* Fallback to the previous state if the user doesn't push changes
* Set up GitLab as a remote provider
* Change some settings by going to: **Settings** ---> Edit your **Sync provider**
* Edit the details by:
* Switching from a single file (`tokens.json`) to a multifile setup (`themes`)
* Switching branches
* Pushing to the remote should work as expected
=> fix: allow GitLab edits to create & switch across new branches and source files

.changeset/spotty-parents-train.md, packages/tokens-studio-for-figma/src/app/components/DuplicateResolver/ResolveDuplicateTokenGroup.tsx
Fixes #3068  
- Fixes checkbox for max width value previews.
- Use this tokens JSON
```json
{
"a": {
"test": {
"$type": "color",
"$value": "#0aa"
}
},
"a-copy": {
"test": {
"$type": "color",
"$value": "linear-gradient(180deg, {colors.teal.800}, {colors.teal.800}, {colors.teal.800}, #0fa, {colors.teal.800} , #0fa 100%)"
}
}
}
```
Change `const error ...` in `DuplicateTokenGroupModal` to this (might need to set some types to `any` for the build to pass):
```
const error: any = useMemo(() => null, [isOpen, activeTokenSet, newName, oldName, selectedTokenSets, tokens, type]);
```
- Duplicate the group `a-copy` to `a`
- Open the duplicate resolve modal button in the footer.
- Verify that the radio checkbox isn't stretched
=> Fix checkbox UI for duplicate resolve modal

.changeset/calm-carrots-sit.md, packages/tokens-studio-for-figma/package.json, packages/tokens-studio-for-figma/src/app/store/useTokens.tsx, packages/tokens-studio-for-figma/src/plugin/TokenValueRetriever.ts, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/createStyles.ts, packages/tokens-studio-for-figma/src/plugin/updateStyles.ts, packages/tokens-studio-for-figma/src/types/AsyncMessages.ts
Addresses #3088 - the themes that are now selected in the styles export modal shall be exported as styles.
Resolves #3083  - the 2nd point when multiple themes are enabled, then the styles don't show in Figma
- When we select the themes in the export modal to be exported as styles, the expectation now would be to export those themes regardless of their active/inactive status.
- When multiple themes are enabled, especially core/global, figma ceased to display the corresponding style token applied. This PR should address that
1st Issue:
* Create some themes in the plugin.
* Keep them inactive.
* Go to Export Styles&Variables, choose the themes you wish to be exported as styles
* They should be exported irrespective of them being inactive
2nd Issue:
- Create some themes, along with a …
=> Fix styling issues post 2.0 release

.changeset/cyan-fireants-sparkle.md, packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ExportSetsTab.tsx
Small fix to a missing padding issue in Export Sets Tab
Before:
After:
=> Fix padding in export sets and add gap between sets

packages/tokens-studio-for-figma/src/app/store/providers/ado/ado.tsx, packages/tokens-studio-for-figma/src/app/store/providers/gitlab/gitlab.tsx, packages/tokens-studio-for-figma/src/app/store/remoteTokens.test.ts
👀 Original community thread: https://tokens-studio.slack.com/archives/C02DLQXNY6Q/p1724944973329479
When users were pushing to GitLab, an error saying "Push to remote cancelled!" appeared on the modal, although it all works as expected.
For GitLab & ADO, pushing to remote will actually fail, not showing this falsy error. 
* Edit details in GitLab / ADO as a provider
* Follow the push to remote flow
* See successful edits in remote OR see error if you cancel the flow
https://github.com/user-attachments/assets/b091aef2-98c5-44c1-879f-ccd7b502668e
https://github.com/user-attachments/assets/2af8d67c-b38d-41b2-b574-427c1cc5efa7
=> fix: prevent falsy error when pushing to remote (GitLab & ADO)

.changeset/orange-donkeys-chew.md, packages/tokens-studio-for-figma/src/plugin/TokenValueRetriever.ts, packages/tokens-studio-for-figma/src/plugin/__tests__/setValuesOnNode.test.ts
Follow Up PR to fix styling issue where styles are not being applied when sets are being exported as styles(with ignore first part of token names for styles selected)
Fixes the issue where styles are not being applied when sets are being exported as styles (with ignore first part of token names for styles selected)
- Create some themes with enabled sets in the plugin
- Export selected sets as styles
- Make sure to check the 'Ignore First Part of token name for Styles' option
- Choose the sets to export as styles and export to Figma
- Apply token from a the active theme where the set belongs
- The corresponding style should now be applied
=> Fix export sets

.changeset/wet-ways-hear.md, packages/tokens-studio-for-figma/src/app/components/ImportedTokensDialog.test.tsx, packages/tokens-studio-for-figma/src/app/components/ImportedTokensDialog.tsx, packages/tokens-studio-for-figma/src/app/store/models/tokenState.tsx, packages/tokens-studio-for-figma/src/app/store/useManageTokens.tsx, packages/tokens-studio-for-figma/src/plugin/pullVariables.test.ts, packages/tokens-studio-for-figma/src/plugin/pullVariables.ts
Fixes speed of variable creation by ... perceived 100x
Fixes https://github.com/tokens-studio/figma-plugin/issues/3122
Properly import variables by not doing it one by one but rather in one swift swoop
Import variables into tokens... also test if you can update existing ones properly as expected
=> fix import of variables speed

.changeset/purple-chairs-learn.md, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/attachLocalVariablesToTheme.ts, packages/tokens-studio-for-figma/src/plugin/createLocalVariablesInPlugin.ts, packages/tokens-studio-for-figma/src/plugin/createLocalVariablesWithoutModesInPlugin.ts, packages/tokens-studio-for-figma/src/plugin/generateTokensToCreate.test.ts, packages/tokens-studio-for-figma/src/plugin/generateTokensToCreate.ts, packages/tokens-studio-for-figma/src/plugin/setNumberValuesOnVariable.ts, packages/tokens-studio-for-figma/src/plugin/updateVariables.ts, packages/tokens-studio-for-figma/src/types/ExportTokenSet.ts, packages/tokens-studio-for-figma/src/utils/getTokenSetsOrder.test.ts, packages/tokens-studio-for-figma/src/utils/getTokenSetsOrder.ts, packages/tokens-studio-for-figma/src/utils/sortSets.test.ts, packages/tokens-studio-for-figma/src/utils/sortSets.ts, packages/tokens-studio-for-figma/src/utils/tokenHelpers.ts
Closes https://github.com/tokens-studio/figma-plugin/issues/3139
When we're merging token sets, we weren't ordering token sets as they should. Instead, we were relying on the ordering that existed in the themes. This caused any variable creation or merging of token sets to not respect overrides coming later.
This PR fixes this. In addition, this PR fixes a bug when exporting tokens via Sets - given they both were using that same function I fixed that along the way. Basically, if you exported sets that had math calculations inside, we didnt properly calculate those, as we were only passing in the current set tokens, and not the whole tokens when resolving.
Load the .JSON linked in the Issue (single file import). Try to create before and after.
=> fix override order

.changeset/yellow-doors-fail.md, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/__tests__/getThemeReferences.test.ts, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/__tests__/resolveVariableInfo.test.ts, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/getThemeReferences.ts, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/resolveVariableInfo.ts, packages/tokens-studio-for-figma/src/plugin/createLocalVariablesInPlugin.ts, packages/tokens-studio-for-figma/src/plugin/createLocalVariablesWithoutModesInPlugin.ts, packages/tokens-studio-for-figma/src/plugin/getVariablesWithoutZombies.test.ts, packages/tokens-studio-for-figma/src/plugin/getVariablesWithoutZombies.ts, packages/tokens-studio-for-figma/src/plugin/mergeVariableReferences.test.ts, packages/tokens-studio-for-figma/src/plugin/mergeVariableReferences.ts, packages/tokens-studio-for-figma/src/plugin/pullVariables.test.ts, packages/tokens-studio-for-figma/src/plugin/pullVariables.ts, packages/tokens-studio-for-figma/src/plugin/renameVariablesFromPlugin.test.ts, packages/tokens-studio-for-figma/src/plugin/renameVariablesFromPlugin.ts, packages/tokens-studio-for-figma/src/plugin/updateVariables.test.ts, packages/tokens-studio-for-figma/src/plugin/updateVariables.ts, packages/tokens-studio-for-figma/src/plugin/updateVariablesFromPlugin.test.ts, packages/tokens-studio-for-figma/src/plugin/updateVariablesFromPlugin.ts, packages/tokens-studio-for-figma/src/utils/getVariablesMap.ts, packages/tokens-studio-for-figma/tests/__mocks__/figmaMock.d.ts, packages/tokens-studio-for-figma/tests/__mocks__/figmaMock.js
Closes https://github.com/tokens-studio/figma-plugin/issues/3140
This adds a check before we gather variables to use for references or for application, to see if the variable collection of those variables still exists.
Open a file affected by this bug (hard to replicate). File in DM with `@rbosker` has this: https://hyma-team.slack.com/archives/D03HL8WE738/p1726231101338089 - https://www.figma.com/design/foDPZl0c28gzctr6ztvNfy/Components-Roberto-(Copy)?t=I2ASNxMojuiwTyTv-0
=> fix zombie variables

packages/tokens-studio-for-figma/src/plugin/updateVariables.test.ts, packages/tokens-studio-for-figma/src/plugin/updateVariables.ts
fixes an issue i discovered during release that didnt properly populate the list of available variables when creating
=> fixes an issue from zombie variables on variable create

.changeset/spotty-games-sin.md, packages/tokens-studio-for-figma/src/storage/BitbucketTokenStorage.ts
Fixes #3117 
Fixes a bug with Bitbucket sync issue where a deleted set's json still reflects in the repo.
* Sync Tokens with Bitbucket
* Delete a token set in the plugin
* Sync again with bitbucket
* The json file of the deleted set should now be removed.
=> Fix bitbucket empty sets

.changeset/warm-buses-bathe.md, packages/tokens-studio-for-figma/src/plugin/TokenValueRetriever.ts
Fixes #3145 
Fixes a bug around applying styles with prefixed theme name, where if the user applies core theme, then it mangles with the application of styles display in the plugin.
* Create themes in the plugin
* Export them as styles with prefixed theme name
* Apply a color token from a theme, it will reflect the style in Figma
* Now disable core style and it should work then
=> Fix styling issue with prefixed theme name

.changeset/weak-oranges-buy.md, packages/tokens-studio-for-figma/src/plugin/__tests__/setValuesOnNode.test.ts, packages/tokens-studio-for-figma/src/plugin/applyTypographyTokenOnNode.ts
Addresses #3118 
Fixes a bug occurring when a user applies a typography token on a text node, and then applies another token, tinkering with an individual typography property(like font size or font family, etc.), and the user clicks on 'Apply to selection', the typography token overrides the individual token property, which is not expected behaviour.
* Create a typography token with references
* Apply the token to a text
* Apply a any token overriding one of the typography properties(like font size, or font family)
* Then Apply to selection
* The individual token typography should be applied and work as expected
=> fix typography tokens resolution

.changeset/twenty-days-relate.md, packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts
Fixes #3150  
Steps to reproduce the behavior:
1. Create a gradient, for example: `linear-gradient(45deg, #ff00ff 0%, #ff0000 100%)`
2. Reference this gradient in another token (in the same or other set)
3. Export these as Styles in Figma
**Before**
**After**
=> apply linear gradient incase variable reference not resolved

.changeset/perfect-fishes-smoke.md, packages/tokens-studio-for-figma/src/app/store/models/tokenState.tsx
Closes #3135
Normalizes old token value and new token value descriptions before comparing equality.
🚧 Could use some help with adding a test, I am unfamiliar with the state setup used in the project. 
In basis, the old value contains a description value of an empty string and the new description contains a value of `undefined`.
=> fix(tokenState): setTokensFromVariables description comparison

.changeset/heavy-colts-look.md, packages/tokens-studio-for-figma/src/utils/isSameCredentials.test.ts, packages/tokens-studio-for-figma/src/utils/isSameCredentials.ts
Closes https://github.com/tokens-studio/figma-plugin/issues/3069
Our check for if a sync provider is active was missing logic to compare the unique `internalId` when available for some sync providers. This PR elevates that to always check for those, if present. Also updates tests.
Note: The `internalId` was something that we added 2 years back now or so. So we should in *most* cases have it, it might just be the case for _really_ old examples that we dont have it.
- Add tests
- Update logic of uniqueness check
Add a Studio sync provider with two different API keys.
Old version = shows up twice
New version = active state shown properly
=> update isSameCredentials check to prefer internalId when available

packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json, packages/tokens-studio-for-figma/src/utils/__tests__/uiSettings.test.ts, packages/tokens-studio-for-figma/src/utils/uiSettings.ts
This PR changes behavior of `Update styles` to be `false` by default, as per internal feedback.
Also changes the copy to be a bit easier to understand what's happening when this setting is on.
=> Change default of update styles to false, update copy

.changeset/old-pots-yell.md, packages/tokens-studio-for-figma/src/storage/BitbucketTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/__tests__/BitbucketTokenStorage.test.ts
We're not able to pull updates in Figma app for 15 minutes due to Cache-Control header.
Disables cache for Bitbucket requests
Open plugin in Figma app and check if pulling is cached
=> Disable cache for Bitbucket

.changeset/healthy-rabbits-fetch.md, packages/tokens-studio-for-figma/src/storage/BitbucketTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/__tests__/BitbucketTokenStorage.test.ts
Fixes #3196 
This PR increases the amount of json files returned to 100, which is the maximum allowed from their API.
The default was 10, hence the users were unable to fetch the set json files, when the number of sets was beyond 10.
- Create a token set subfolder with more than 10 sets.
- Push it to Bitbucket.
- Then pull it from the same repo.
- Now it will should be pulling all the sets(unless the count is more than 100)
=> Fix bitbucket sync

.changeset/wet-avocados-cheat.md, packages/tokens-studio-for-figma/src/storage/BitbucketTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/__tests__/BitbucketTokenStorage.test.ts
Closes #3197 
Fixes sync with Bitbucket provider:
- pull when the option is to syng with a single file was not working 
- push was removing all other .json files in the selected folder (either root of the chosen folder)
Sync tokens with Bitbucket. Pull, change, push should work. Both way sync should work.
=> fix(3197): Fix sync with Bitbucket

.changeset/shiny-boats-collect.md, packages/tokens-studio-for-figma/src/storage/GitlabTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/__tests__/GitlabTokenStorage.test.ts
Fixes a very specific issue in gitlab sync, where in when a user is trying to load tokens in a repo, the "Initial Commit" message is causing an error because the commit message is not in line with the user's company's commit message rules.
Addresses #3239 
This PR replaces the 'Initial commit' message with the message the user puts in for their first commit instead
- Create a repo in Gitlab with commit message rules regex
- Push the tokens to the repository following the message format
- It should now sync normally as expected without throwing an error unless the user's message in not conforming to the commit message policy
https://tokens-studio.slack.com/archives/C08674X9DHU/p1735214682471059?thread_ts=1735214100.463429&cid=C08674X9DHU
=> fix gitlab commit message error

.changeset/large-foxes-reply.md, packages/tokens-studio-for-figma/package.json, packages/tokens-studio-for-figma/src/app/store/models/reducers/__tests__/tokensStudio.test.ts, packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/createThemeGroupMutation.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/getProjectDataQuery.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/graphql/updateThemeGroupMutation.ts, packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio/index.ts, yarn.lock
* TS sync removed some metadata from themes like figmaModeId or figmaCollectionId. Fixed this issue by querying for that data and also updating it properly.
* Also updated the types and sdk packages
Closes #0000
=> Fix ts theme metadata

.changeset/gentle-pets-confess.md, packages/tokens-studio-for-figma/src/storage/GitlabTokenStorage.ts
Fixes an issue in Gitlab sync. When a user pushes a change as a commit, gitkeep file is being created, leading to 3 commits for each change.
- Create a sync in Gitlab Repo
- Make a change
- Commit the change
- It should now be only one commit(if gitkeep file was already removed previously)
=> Fix gitlab bug, gitkeep file created on every commit

.changeset/rotten-ads-roll.md, packages/tokens-studio-for-figma/src/app/components/StorageItem.tsx, packages/tokens-studio-for-figma/src/app/store/remoteTokens.tsx
Resolves #3259 
Currently, if the local storage or previous sync provider had tokens set in Legacy format, while switching to Tokens Studio Sync provider, it was being set to Leagcy as well, inspite of the tokens beign received from studio in DTCD format.
also, hides the badge of Legacy/DTCG in studio sync storage type as the default will always be DTCG
- Create a sync provider in the plugin from studio
- Switch to Local Storage, change format to legacy
- Switch back to Tokens Studio storage and it should be set to DTCG by default again
=> Fix default Token Format for Studio sync as DTCG

.changeset/cold-fishes-attend.md, packages/tokens-studio-for-figma/src/storage/GitlabTokenStorage.ts
Fixes #3282 
When a user is syncing tokens in gitlab with a single tokens json file, the commits end up deleting the other json files(like package.json, package-lock.json)
This PR just adds a check before the deletion process in gitlab to check whether the tokens are being stored in a single json file. If yes, then it will not delete any files.
- Sync tokens in a gitlab repo with single token json file
- Add another json file like package.json in the same repo
- Push commits to the tokens.json
- It will not delete other files
=> fix json file deletion for single file tokens storage commits

.changeset/wet-jeans-approve.md, packages/tokens-studio-for-figma/src/plugin/pullVariables.ts
When a user imports variables, and themes are created from that variable, the correct token applied is not working when a particular theme is applied.
This PR simply links the correct variable id to the theme and set, which enables figma to detect the right variable applied
- Import variable collections
- Select any theme
- Apply a token to a frame
- It should now display the correct corresponding variable applied.
=> fix variable id assigned to themes created from variable import

.changeset/metal-mangos-fold.md, packages/tokens-studio-for-figma/package.json, packages/tokens-studio-for-figma/src/constants/SharedPluginDataKeys.ts, packages/tokens-studio-for-figma/src/figmaStorage/FigmaStorageProperty.ts, packages/tokens-studio-for-figma/src/figmaStorage/IsCompressedProperty.ts, packages/tokens-studio-for-figma/src/figmaStorage/ThemesProperty.ts, packages/tokens-studio-for-figma/src/figmaStorage/ValuesProperty.ts, packages/tokens-studio-for-figma/src/figmaStorage/__tests__/ThemesProperty.test.ts, packages/tokens-studio-for-figma/src/figmaStorage/__tests__/ValuesProperty.test.ts, packages/tokens-studio-for-figma/src/figmaStorage/index.ts, packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/__tests__/update.test.ts, packages/tokens-studio-for-figma/src/plugin/node.ts, packages/tokens-studio-for-figma/src/utils/figma/updateLocalTokensData.ts, yarn.lock
Closes #3328 
This PR compresses the data(mainly tokens and themes), using lz-string, while storing it in the localSharedPluginData of a user's file. While reading it decompresses it first.
Also, for legacy data, or users opening the plugin after a long time, it will still check whether their data is compressed or not, using a key added in this PR called `isCompressed`, which is also stored in the sharedPluginData, which once set to true,i.e the user is now storing compressed data, cannot be set to false again
- Testing this is tricky and not straightforward
- Pull this branch, open the plugin, preferably with data and check if it opens fine
- then run this on the console to see if the data is compressed or not
- `figma.root.getSharedPluginData('tokens','themes');` - should return …
=> compress shared Plugin Data token values

.changeset/silver-experts-sin.md, packages/tokens-studio-for-figma/src/plugin/figmaTransforms/convertFontFamilyToFigma.ts
Closes https://github.com/tokens-studio/figma-plugin/issues/3331
Before we were relying on font family to be a string, however some users have numerical family names.
Converts to string before we trim
=> fix numerical family names

packages/tokens-studio-for-figma/src/app/components/Footer.tsx, packages/tokens-studio-for-figma/src/app/store/models/tokenState.tsx, packages/tokens-studio-for-figma/src/app/store/updateSources.tsx, packages/tokens-studio-for-figma/src/selectors/index.ts, packages/tokens-studio-for-figma/src/selectors/themesSizeSelector.ts
To display size check indicator for themes size above 100KB as well.
Currently the size check warning indicator is active only when the compressed Tokens size is greater than 100KB
This PR triggers the size indicator for the themes size as well, since the themes can also take up more than 100KB from the shared Plugin Data as well.
=> display size check indicator for themes above 100KB as well

packages/tokens-studio-for-figma/src/figmaStorage/FigmaStorageProperty.ts, packages/tokens-studio-for-figma/src/figmaStorage/__tests__/CheckForChangesProperty.test.ts, packages/tokens-studio-for-figma/src/figmaStorage/__tests__/ThemesProperty.test.ts, packages/tokens-studio-for-figma/src/figmaStorage/__tests__/UsedTokenSetProperty.test.ts, packages/tokens-studio-for-figma/src/figmaStorage/__tests__/ValuesProperty.test.ts, packages/tokens-studio-for-figma/src/plugin/node.ts, packages/tokens-studio-for-figma/src/utils/__tests__/splitIntoChunks.test.ts, packages/tokens-studio-for-figma/src/utils/figma/updateLocalTokensData.ts, packages/tokens-studio-for-figma/src/utils/figmaStorage/__tests__/readSharedPluginData.test.ts, packages/tokens-studio-for-figma/src/utils/figmaStorage/__tests__/writeSharedPluginData.test.ts, packages/tokens-studio-for-figma/src/utils/figmaStorage/readSharedPluginData.ts, packages/tokens-studio-for-figma/src/utils/figmaStorage/writeSharedPluginData.ts, packages/tokens-studio-for-figma/src/utils/splitIntoChunks.ts
While using SharedPluginData in Figma, users currently have the freedom to store any amount of data.
However, starting May 13th, figma will impose a data limit of 100KB per key in sharedPluginData.
As a workaround we decided to chunk the themes and values into multiple keys while writing if their compressed size, surpasses 95KB, so for every 95KB, there will be a key generated like themes_chunk_0, themes_chunk_1, values_chunk_0, values_chunk_1, and so on. 
Also, added keys like themes_meta and values_meta will store the amount of chunks that have been created so that it is easy while reading and combining the same data.
- Switch to local storage
- Load a token set/themes with compressed size greater than 100KB
- Then go to Figma dev console, type …
=> Chunk Themes and Values when they cross 95KB in storage

packages/tokens-studio-for-figma/src/app/store/models/reducers/tokenState/setTokenData.ts
When the plugin loads, the indicator displays the indicator if the tokens/themes size is greater than 100KB.
=> fix size check indicator on plugin load

.changeset/heavy-pugs-divide.md, packages/tokens-studio-for-figma/src/figmaStorage/ClientStorageProperty.ts
Fixed an issue that was causing checkForChanges to not be read correctly, causing a 'not a function'
=> Fix read method to return correct data for 'checkForChanges' key

packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts
Closes #3425 
We are observing that when users are attempting to export sets with huge tokens, (typically >1000 atleast), the plugin is freezing and then crashing.
Error logs point to a memory leakage on Figma's end. This PR addresses our approach to handle such huge sets.
This PR changes the approach to manage such huge tokens in batches of 100, instead of processing all at one, if token count is above 1000.
- Export a  large token set (e.g., 1000+ tokens).
- This should now display progress bar and the plugin shouldn't crash, due to the memory leakage issue
=> Fix plugin crashing when a huge token set is exported to variables

.changeset/unlucky-starfishes-decide.md, packages/tokens-studio-for-figma/src/app/store/models/effects/tokenState/setDefaultTokens.ts, packages/tokens-studio-for-figma/src/app/store/remoteTokens.tsx
=> Fix load tokens when imported

.changeset/curvy-needles-nail.md, packages/tokens-studio-for-figma/src/plugin/__tests__/applyBorderWidthValuesOnNode.test.ts, packages/tokens-studio-for-figma/src/plugin/__tests__/setValuesOnNode.test.ts, packages/tokens-studio-for-figma/src/plugin/applyBorderWidthValuesOnNode.ts
Closes #3439 
This Pull Request adds a check while applying stroke weight to a node, whether the node has properties like strokeweighttop, left, etc(for rectangule/frame nodes), then checks variable application for each corner.
If it doesn't have corners, then does a check only for strokeweight property of the node(if that exists) and applied variable to that shape(like oval, ellipses, text, etc.)
- Create an oval, ellipse/text node
- Create a border width token and export as variable
- now apply the border width as stroke on these shapes
- it should be applied as a variable
=> fix border width not applying on ellipses as variable references in Figma

.changeset/fast-toes-approve.md, packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx, packages/tokens-studio-for-figma/src/types/tokens/SingleNumberToken.ts, packages/tokens-studio-for-figma/src/utils/TokenResolver.ts, packages/tokens-studio-for-figma/src/utils/getResolvedTextValue.ts, packages/tokens-studio-for-figma/src/utils/mapTokensToVariableInfo.ts, packages/tokens-studio-for-figma/src/utils/processNumberValue.test.ts, packages/tokens-studio-for-figma/src/utils/processNumberValue.ts, packages/tokens-studio-for-figma/src/utils/stringifyTokens.ts, packages/tokens-studio-for-figma/src/utils/trimValue.test.ts, packages/tokens-studio-for-figma/src/utils/trimValue.ts
Closes #3465 
Currently number tokens are displayed as strings in the json file export/editor
According to DTCG format, it should be displayed in numeric format without quotes, this PR addresses that concern and will now be displayed with appropriate format.
- Create a numeric token
- Go to JSON editor and check how is it being displayed
=> Fix number tokens display in json
